Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2022-12, with the labels that each got.

#169 updated the loading state of the appointments to reflect loading or i…
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#170 Booth/update finalize
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/IdBirthInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/PersonalInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/PhysicalAppearanceStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/WorkInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AliasInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AddressTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AliasTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/WeaponsTable.spec.ts.snap
Labels: main, UI

#172 Booth/update finalize
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#174 AB # bug fix
  UI/apps/admin/src/AdminApp.vue
Labels: main, UI

#175 AB # bug fix
  Documentation/UserInterface/README.md
Labels: Documentation, main

#177 updated the renew path to match normal path
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
Labels: main, UI

#178 Booth/renew path updates
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/tests/unit/components/containers/AcknowledgementContainer.spec.ts
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/ApplicationTypeStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/FileUploadStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/PersonalInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#179 #AB Fix ADA, PWA navigation
  UI/apps/admin/public/manifest.json
  UI/apps/public/public/manifest.json
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/utils/tests/formatters/defaultFormatters.spec.ts
Labels: main, UI

#180 improve some ADA
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/containers/MoreInformationConatainer.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
Labels: main, UI

#181 AB # Fix character limit
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/CommentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
Labels: main, UI

#184 update the signature step
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/senders/documentSenders.ts
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/SignatureStep.vue
Labels: main, UI

#185 Add Jwt and bug fix admin settings
  API/CCW.Admin/CCW.Admin.csproj
  API/CCW.Admin/Mappers/EntityToAgencyProfileSettingsResponseModelMapper.cs
  API/CCW.Admin/Program.cs
  API/CCW.Admin/appsettings.Development.json
  API/CCW.Application/CCW.Application.csproj
  API/CCW.Application/Program.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/CCW.Document.csproj
  API/CCW.Document/Program.cs
  API/CCW.Document/appsettings.Development.json
  API/CCW.Payment/CCW.Payment.csproj
  API/CCW.Payment/Program.cs
  API/CCW.Payment/appsettings.Development.json
  API/CCW.Schedule/CCW.Schedule.csproj
  API/CCW.Schedule/Program.cs
  API/CCW.Schedule/appsettings.Development.json
  API/CCW.UserProfile/Program.cs
Labels: main, API

#186 update the agency information display
  UI/libs/core-public/src/lib/components/containers/MoreInformationConatainer.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#190 Requested changes
  API/CCW.Admin/CCW.Admin.csproj
  API/CCW.Admin/Program.cs
  API/CCW.Application.Tests/MapperTests.cs
  API/CCW.Application/CCW.Application.csproj
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/BackgroudCheck.cs
  API/CCW.Application/Entities/QualifyingQuestions.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToBackgroudCheckMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToQualifyingQuestionsMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationToBackgroundCheckMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationToQualifyingQuestionsMapper.cs
  API/CCW.Application/Program.cs
  API/CCW.Common/AuthorizationPolicies/IsAdminHandler.cs
  API/CCW.Common/AuthorizationPolicies/IsProcessorHandler.cs
  API/CCW.Common/AuthorizationPolicies/IsSystemAdminHandler.cs
  API/CCW.Common/AuthorizationPolicies/RoleRequirement.cs
  API/CCW.Common/CCW.Common.csproj
  API/CCW.Document/CCW.Document.csproj
  API/CCW.Document/Program.cs
  API/CCW.Payment/CCW.Payment.csproj
  API/CCW.Payment/Program.cs
  API/CCW.Schedule/CCW.Schedule.csproj
  API/CCW.Schedule/Program.cs
  API/CCW.UserProfile/AuthorizationPolicies/IsAdminHandler.cs
  API/CCW.UserProfile/AuthorizationPolicies/IsProcessorHandler.cs
  API/CCW.UserProfile/AuthorizationPolicies/IsSystemAdminHandler.cs
  API/CCW.UserProfile/AuthorizationPolicies/RoleRequirement.cs
  API/CCW.UserProfile/CCW.UserProfile.csproj
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
  API/CCW.sln
Labels: main, API

#191 fixed switch statement
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
Labels: main, UI

#192 AB #2093 - fix radio default state, cleanup
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/views/MoreInformationView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/RenewFormStepItems.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/RenewSecondFormStepItems.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/composables/useEnvName.ts
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/ui/src/lib/wrappers/FormWrapper.vue
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/WorkInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AliasInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AddressTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AliasTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/WeaponsTable.spec.ts.snap
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#193 Booth/update
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/SignatureStep.vue
Labels: main, UI

#194 fix getAll
  UI/apps/admin/src/AdminApp.vue
Labels: main, UI

#196 Booth/update
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
Labels: main, UI

#197 removed s
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#198 Add common project, add auth, and search endpoint
  API/CCW.Admin/CCW.Admin.sln
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Admin/Program.cs
  API/CCW.Application/CCW.Application.sln
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Common/Class1.cs
  API/CCW.Document/CCW.Document.sln
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Payment/CCW.Payment.sln
  API/CCW.Schedule/CCW.Schedule.sln
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Program.cs
Labels: main, API

#199 Remove auth from download logo
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#200 Fix Interceptor JWT token
  UI/libs/core-public/src/lib/api/interceptors.ts
Labels: main, UI

#201 Fix jwt auth b2c
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Program.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Program.cs
  API/CCW.Payment/Program.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Program.cs
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Program.cs
Labels: main, API

#203 Booth/UI feedback changes
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewContactInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#207 Agency file endpoint
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Admin/Program.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Program.cs
  API/CCW.Document.Tests/AzureStorageTests.cs
  API/CCW.Document.Tests/DocumentControllerTests.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Program.cs
  API/CCW.Document/Services/AzureStorage.cs
  API/CCW.Document/Services/IAzureStorage.cs
  API/CCW.Payment/Program.cs
  API/CCW.Schedule/Program.cs
  API/CCW.UserProfile/Program.cs
Labels: main, API

#208 final change to the upload
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#209 removed history and add livescan
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#210 added the age check to the dob
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
Labels: main, UI

#213 AB #2144 #2123 #2151 - Fix feedback items
  UI/apps/admin/config/config.json
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/permits/__snapshots__/Permits.spec.ts.snap
Labels: main, UI

#215 Andrew/infra
  Deployment/IaC/Infrastructure/adminapi.json
  Deployment/IaC/Infrastructure/bicep/main.bicep
  Deployment/IaC/Infrastructure/bicep/main.json
  Deployment/IaC/Infrastructure/bicep/main.parameters.json
  Deployment/IaC/Infrastructure/bicep/modules/CosmosDB.bicep
  Deployment/IaC/Infrastructure/bicep/modules/appConfig.bicep
  Deployment/IaC/Infrastructure/bicep/modules/storageAccount.bicep
  Deployment/IaC/Infrastructure/otherResources.json
  Deployment/IaC/Infrastructure/placeholder.txt
  Deployment/IaC/Infrastructure/sandboxTemplate.json
  Deployment/IaC/Infrastructure/sandboxTemplate.parameters.json
  Deployment/IaC/Marketplace/.gitignore
  Deployment/IaC/Marketplace/CSSA-Agency-Names-Abbreviations.xlsx
  Deployment/IaC/Marketplace/New-AzureMarketplacePackage.ps1
  Deployment/IaC/Marketplace/README.md
  Deployment/IaC/Marketplace/Updates/.gitignore
  Deployment/IaC/Marketplace/Updates/createUiDefinition.json
  Deployment/IaC/Marketplace/Updates/mainTemplate.json
  Deployment/IaC/Marketplace/createUiDefinition.json
  Deployment/IaC/Marketplace/mainTemplate.json
  Deployment/IaC/Marketplace/placeholder.txt
  Deployment/IaC/README.MD
  Deployment/Pipelines/azure-pipelines-iac.yml
  Deployment/Pipelines/templates/dev-002-vars.yml
  Deployment/Pipelines/templates/dev-003-vars.yml
  Deployment/Pipelines/templates/logging_tasks.yml
  Templates/README.MD
Labels: main, IaC

#216 AB # Token expiry handling, invalid file input fix,
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-public/src/lib/api/interceptors.ts
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/ApplicationTypeStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/ContactStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FileUploadStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/PersonalInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/PhysicalAppearanceStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/WorkInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/login/__snapshots__/LoginButton.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/dialogs/SessionExpiredDialog.vue
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#214 changes for 2150,2158,2159
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/views/MoreInformationView.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#217 Add delete application endpoint
  API/CCW.Application.Tests/CosmosDbServiceTests.cs
  API/CCW.Application.Tests/PermitApplicationControllerTests.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#218 AB # Initial UI marketplace
  Deployment/IaC/Marketplace/createUiDefinition.json
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
Labels: main, UI, IaC

#219 AB #2146 Search Query
  Deployment/IaC/Marketplace/createUiDefinition.json
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/ApplicationTypeStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/ContactStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FileUploadStep.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, IaC

#220 Undo changes for applicant download file
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#221 fixes for 2160, 2165,2169
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
Labels: main, UI

#223 Dcoument in line, and fix application getAll bug
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Services/AzureStorage.cs
Labels: main, API

#224 fixed merge issues
  Deployment/Pipelines/azure-pipelines-iac.yml
  UI/libs/core-public/tests/unit/components/form-steps/IdBirthInfoStep.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/PhysicalAppearanceStep.spec.ts.snap
Labels: main, UI, IaC

#226 Fix doc inline
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#225 fixed some of the steps still updating history
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#227 AB #2149 - Dark mode issues
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-admin/tests/unit/components/permits/__snapshots__/Permits.spec.ts.snap
Labels: main, UI

#228 AB #2190 silent tokens, upload fix
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/composables/useInterval.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
Labels: main, UI

#229 Remove inline for doc download png
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Document/CCW.Document.csproj
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#231 update to add inline for pdf online
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#230 added the fixes for 2188 2150 2184, 2187
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#232 Ab # fix silent token
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
Labels: main, UI

#233 Ab #2174 - Add reschedule
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/ContactStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/IdBirthInfoStep.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
Labels: main, UI

#234 AB #2115 - fix search query
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-public/src/lib/api/interceptors.ts
Labels: main, UI

#235 Bug submit app, case insensitive search
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
Labels: main, API

#236 fixes for 2183, 2186
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#237 updated the state text fields.
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
Labels: main, UI

#238 AB #2203 Silent Refresh
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
Labels: main, UI

#239 Booth/locking finalize
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewContactInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/DeleteDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#240 updated the hints for the qualifying questions
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#241 updated Application fields
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/SpouseInformation.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Enum/PaymentStatus.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToSpouseInformationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToUserApplicationMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationToSpouseInformationMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/UserRequestPermitApplicationToSpouseInformationMapper.cs
Labels: main, API

#242 AB#2195 payment lock and api updates
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#243 AB#2215 spouse fields update
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
Labels: main, UI

#244 AB#2229 fixes for 2229 and 2225 and idea for 2191
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/FinalizeContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
Labels: main, UI
