Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2022-09, with the labels that each got.

#2 GIT Automated branching strategy
  README.md
  git.sh
Labels: main

#6 #1773 - Enforce Vue recommended standards
  .gitignore
  README.md
  UI/README.MD
  UI/apps/admin/.eslintrc.json
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/.eslintrc.json
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/.eslintrc.json
  UI/libs/core-admin/src/lib/components/Button.vue
  UI/libs/core-public/.eslintrc.json
  UI/libs/core-public/src/lib/components/Button.vue
  UI/libs/core-public/src/lib/views/FormView.vue
  UI/libs/shared/ui/.eslintrc.json
  UI/libs/shared/ui/src/lib/components/Button.vue
  UI/libs/shared/ui/src/lib/components/containers/FormContainer.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/shared/utils/.eslintrc.json
Labels: main, UI

#8 Booth/dev
  UI/apps/admin/src/main.ts
  UI/apps/public/src/PublicApp.vue
  UI/apps/public/src/main.ts
  UI/libs/core-admin/.storybook/main.js
  UI/libs/core-admin/src/lib/store/index.ts
  UI/libs/core-public/.storybook/main.js
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/FormContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/store/index.ts
  UI/libs/core-public/src/lib/views/FormView.vue
  UI/libs/shared/ui/.storybook/main.js
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/alerts/FormErrorAlert.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/shared/ui/src/lib/components/inputs/CheckboxInput.vue
  UI/libs/shared/ui/src/lib/components/inputs/RadioGroupInput.vue
  UI/libs/shared/ui/src/lib/components/inputs/TextInput.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/helpers/storeHelpers/aliasActions.ts
  UI/libs/shared/ui/src/lib/helpers/storeHelpers/personalInfoActions.ts
  UI/libs/shared/ui/src/lib/plugins/vuetify.ts
  UI/libs/shared/ui/src/lib/types/defualtTypes.ts
Labels: main

#14 Booth/create tests
  UI/jest.config.ts
  UI/jest.setup.ts
  UI/libs/core-admin/.storybook/main.js
  UI/libs/core-public/.storybook/main.js
  UI/libs/core-public/jest.config.ts
  UI/libs/core-public/jest.setup.ts
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/tests/unit/components/containers/FormButtonContainer.spec.ts
  UI/libs/core-public/tests/unit/components/dialogs/AliasDialog.spec.ts
  UI/libs/core-public/tests/unit/components/dialogs/PreviousAddressDialog.spec.ts
  UI/libs/shared/ui/.storybook/main.js
  UI/libs/shared/ui/jest.config.ts
  UI/libs/shared/ui/jest.setup.ts
  UI/libs/shared/ui/src/lib/components/alerts/FormErrorAlert.vue
  UI/libs/shared/ui/src/lib/components/inputs/CheckboxInput.vue
  UI/libs/shared/ui/src/lib/components/inputs/RadioGroupInput.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/tests/unit/components/AddressTable.spec.ts
  UI/libs/shared/ui/tests/unit/components/AliasTable.spec.ts
  UI/libs/shared/ui/tests/unit/components/CheckboxInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/FormErrorAlert.spec.ts
  UI/libs/shared/ui/tests/unit/components/RadioGroupInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/TextInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/example.spec.ts
  UI/libs/shared/ui/vueShim.d.ts
  UI/package.json
Labels: main

#18 Jarrod/test
  Deployment/IaC/README.MD
  Deployment/Pipelines/README.MD
Labels: main, IaC

#19 Booth/step four
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/inputs/NumberInput.vue
  UI/libs/shared/ui/src/lib/components/inputs/TextInput.vue
  UI/libs/shared/ui/src/lib/store/index.ts
  UI/libs/shared/ui/src/lib/types/defaultTypes.ts
  UI/libs/shared/utils/src/lib/lists/defaultList.ts
Labels: main, UI

#20 #1763 Form step five created.
  UI/.eslintrc.json
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/shared/ui/src/lib/types/defaultTypes.ts
Labels: main, UI

#22 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: main

#23 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: main
