Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2022-11, with the labels that each got.

#99 Booth/update file uploader
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
Labels: main, UI

#101 AB#1953 updated the finalize to inclued a mock payment
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#102 Route changes, Cosmos changes, Add history for application
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/History.cs
  API/CCW.Application/Entities/PermitApplication.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Program.cs
  API/CCW.Document/appsettings.Development.json
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  API/CCW.Schedule/Services/ICosmosDbService.cs
  API/CCW.UserProfile/Controllers/UserController.cs
Labels: main, API

#103 Add Endpoints
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/senders/documentSenders.ts
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
Labels: main, UI

#104 AB#1910 #1878 - Appointment API Integration, Favicons, Icons, Font etc
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Models/AppointmentWindow.cs
  UI/.prettierignore
  UI/apps/admin/public/favicon.ico
  UI/apps/admin/public/img/icons/android-chrome-192x192.png
  UI/apps/admin/public/img/icons/android-chrome-512x512.png
  UI/apps/admin/public/img/icons/apple-touch-icon.png
  UI/apps/admin/public/img/icons/browserconfig.xml
  UI/apps/admin/public/img/icons/favicon-16x16.png
  UI/apps/admin/public/img/icons/favicon-32x32.png
  UI/apps/admin/public/img/icons/favicon.ico
  UI/apps/admin/public/img/icons/mstile-144x144.png
  UI/apps/admin/public/img/icons/mstile-150x150.png
  UI/apps/admin/public/img/icons/mstile-310x150.png
  UI/apps/admin/public/img/icons/mstile-310x310.png
  UI/apps/admin/public/img/icons/mstile-70x70.png
  UI/apps/admin/public/img/icons/safari-pinned-tab.svg
  UI/apps/admin/public/img/icons/site.webmanifest
  UI/apps/admin/public/index.html
  UI/apps/public/public/img/icons/android-chrome-192x192.png
  UI/apps/public/public/img/icons/android-chrome-512x512.png
  UI/apps/public/public/img/icons/apple-touch-icon.png
  UI/apps/public/public/img/icons/browserconfig.xml
  UI/apps/public/public/img/icons/favicon-16x16.png
  UI/apps/public/public/img/icons/favicon-32x32.png
  UI/apps/public/public/img/icons/favicon.ico
  UI/apps/public/public/img/icons/mstile-144x144.png
  UI/apps/public/public/img/icons/mstile-150x150.png
  UI/apps/public/public/img/icons/mstile-310x150.png
  UI/apps/public/public/img/icons/mstile-310x310.png
  UI/apps/public/public/img/icons/mstile-70x70.png
  UI/apps/public/public/img/icons/safari-pinned-tab.svg
  UI/apps/public/public/img/icons/site.webmanifest
  UI/apps/public/public/index.html
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/src/lib/stories/components/appointment/AppointmentScheduler.stories.mdx
  UI/libs/core-admin/src/lib/stories/components/appointment/Appointments.stories.mdx
  UI/libs/core-admin/src/lib/views/Appointment.vue
  UI/libs/core-admin/src/lib/views/AppointmentView.vue
  UI/libs/core-admin/src/lib/views/BrandView.vue
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-admin/src/lib/views/NotFoundView.vue
  UI/libs/core-admin/tests/unit/components/appointment/Appointments.spec.ts
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/shared/ui/src/lib/components/HelloWorld.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#108 Document api changes.
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Program.cs
  API/CCW.Document/Services/AzureStorage.cs
  API/CCW.Document/Services/CosmosDbService.cs
  API/CCW.Document/Services/IAzureStorage.cs
  API/CCW.Document/Services/ICosmosDbService.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
Labels: main, API

#109 Admin settings remove and add new fields
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Admin/Models/AgencyProfileRequestModel.cs
  API/CCW.Admin/Models/AgencyProfileSettings.cs
  API/CCW.Admin/Services/CosmosDbService.cs
Labels: main, API

#110 Booth/api document
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#111 System Settings - Agency
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/router/routes.ts
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-admin/tests/unit/components/brand/BrandForm.spec.ts
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FormView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/src/lib/views/SecondFormView.vue
  UI/libs/core-public/tests/unit/components/form-steps/FormStepTwo.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/composables/useInterval.ts
  UI/libs/shared/utils/tests/formatters/defaultFormatters.spec.ts
Labels: main, UI

#113 Booth/api document
  API/CCW.Document/Controllers/DocumentController.cs
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/RenewFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/RenewSecondFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewSecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewSecondFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
Labels: main, UI, API

#114 AB#1958 - Permits View Initial
  UI/README.MD
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/stories/components/permits/Permit.stories.mdx
  UI/libs/core-admin/src/lib/stories/components/permits/permit-detail/PermitDetail.stories.mdx
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/PermitDetailView.vue
  UI/libs/core-admin/src/lib/views/PermitsView.vue
  UI/libs/core-admin/tests/unit/components/permits/Permits.spec.ts
  UI/libs/core-admin/tests/unit/components/permits/__snapshots__/Permits.spec.ts.snap
  UI/libs/core-public/src/lib/components/form-stepper/RenewSecondFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#116 Booth/form update
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/RenewFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/RenewSecondFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewSecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewSecondFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/containers/FormButtonContainer.spec.ts
  UI/libs/core-public/tests/unit/components/containers/__snapshots__/FormButtonContainer.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#117 AB#1970 completed adding the back button and occupation field.
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewSecondFormWrapper.vue
  UI/libs/core-public/src/lib/views/RenewFormView.vue
Labels: main, UI

#118 AB#1940 integrated the appointment apis with the appointment container
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/senders/appointmentSenders.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI

#120 Fix getAll for when the address is null
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UploadedDocument.cs
  API/CCW.Application/Enum/ApplicationStatus.cs
  API/CCW.Application/Enum/AppointmentStatus.cs
  API/CCW.Application/Mappers/EntityToSummarizedPermitApplicationModelMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToUploadDocumentMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationModelToEntityMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationToUploadDocumentMapper.cs
  API/CCW.Application/Models/PermitApplicationRequestModel.cs
  API/CCW.Application/Models/PermitApplicationResponseModel.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Program.cs
Labels: main, API

#121 Booth/siganture document
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewSecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/inputs/RadioGroupInput.vue
  UI/libs/shared/ui/tests/unit/components/inputs/RadioGroupInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/inputs/__snapshots__/RadioGroupInput.spec.ts.snap
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#124 Booth/UI cleanup
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#125 Booth/reciept page
  UI/libs/core-public/src/lib/components/containers/ApplicationStatusContainer.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/senders/appointmentSenders.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/package.json
Labels: main, UI

#126 Booth/api update
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewSecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewSecondFormWrapper.vue
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
Labels: main, UI

#128 Booth/api update
  UI/libs/core-admin/src/lib/stories/components/footer/Footer.stories.mdx
  UI/libs/core-public/src/lib/components/containers/ApplicationStatusContainer.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/tests/unit/components/containers/__snapshots__/FormButtonContainer.spec.ts.snap
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/AliasDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package.json
Labels: main, UI

#129 AB#1958 - Permit Details Page, Search query with applications, Timeline
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AppointmentInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ImmigrationInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/InterviewQuestionsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/RequestReasonTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-log/PermitLog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/header/__snapshots__/header.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/header/header.spec.ts
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/page-title/PageTitle.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#130 AB#2021 updated the styling for the status page
  UI/libs/core-public/src/lib/components/containers/ApplicationStatusContainer.vue
  UI/libs/core-public/src/lib/components/containers/FinalizeContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/AliasDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementInitial.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AddressInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AppearanceInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/CitizenInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/ContactInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/DOBinfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/PersonalInfoSection.spec.ts.snap
Labels: main, UI

#132 Fix
  UI/apps/public/src/PublicApp.vue
Labels: main, UI

#133 Booth/acknowledgement text
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
Labels: main, UI

#135 AB#1769 API CI/CD Pipelines
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC, API

#137 AB#1892 created the penal code section
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/views/PenalView.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
Labels: main, UI

#139 AB# Fix Dev environment issues
  UI/apps/admin/public/img/icons/site.webmanifest
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/public/img/icons/site.webmanifest
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/composables/useEnvName.ts
Labels: main, UI

#140 feat: update card height to fill page and allow stepper to overflow
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
Labels: main, UI

#141 Fix route names and colors and font sizes for chrome
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DocumentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#142 Booth/stepper update
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewSecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/core-public/tests/unit/components/containers/__snapshots__/FormButtonContainer.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DocumentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/tests/unit/components/acknowledgements/__snapshots__/AcknowledgementPart.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/ContactInfoSection.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#143 Finalized CI/CD for UI websites
  Deployment/Pipelines/azure-pipelines-ui.yml
  Deployment/Scripts/New-UrlRewriteRule.ps1
  Deployment/Scripts/SSL-CustomDomain/SSL-CustomDomain.ps1
  Deployment/Scripts/SSL-CustomDomain/new-cssa-sub-domain.sh
  UI/apps/admin/config/config.json
  UI/apps/public/config/config.json
Labels: main, UI, IaC

#144 Fix for order id
  UI/libs/core-public/src/lib/stores/completeApplication.ts
Labels: main, UI

#145 Ofelia/additional unit tests
  API/CCW.Admin.Tests/AgencyProfileSettingsControllerTests.cs
  API/CCW.Admin.Tests/CosmosDbServiceTests.cs
  API/CCW.Admin.Tests/MapperTests.cs
  API/CCW.Admin/Entities/AgencyProfileSettings.cs
  API/CCW.Admin/Entities/Cost.cs
  API/CCW.Admin/Entities/CostType.cs
  API/CCW.Admin/Mappers/AgencyProfileRequestSettingsModelToEntityMapper.cs
  API/CCW.Admin/Mappers/EntityToAgencyProfileSettingsResponseModelMapper.cs
  API/CCW.Admin/Models/AgencyProfileSettingsRequestModel.cs
  API/CCW.Admin/Models/AgencyProfileSettingsResponseModel.cs
  API/CCW.Admin/Program.cs
  API/CCW.Admin/Services/CosmosDbService.cs
  API/CCW.Application.Tests/CosmosDbServiceTests.cs
  API/CCW.Application.Tests/MapperTests.cs
  API/CCW.Application.Tests/PermitApplicationControllerTests.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/SummarizedPermitApplication.cs
  API/CCW.Application/Mappers/EntityToPermitApplicationResponseMapper.cs
  API/CCW.Application/Mappers/EntityToSummarizedPermitApplicationModelMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToHistoryMapper.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Program.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Schedule.Tests/AppointmentControllerTests.cs
  API/CCW.Schedule.Tests/CosmosDbServiceTests.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.UserProfile.Tests/AutoMoqDataAttribute.cs
  API/CCW.UserProfile.Tests/CCW.UserProfile.Tests.csproj
  API/CCW.UserProfile.Tests/CosmosDbServiceTests.cs
  API/CCW.UserProfile.Tests/MapperTests.cs
  API/CCW.UserProfile.Tests/UnitTest1.cs
  API/CCW.UserProfile.Tests/UserControllerTests.cs
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/CosmosDbService.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
Labels: main, API

#146 AB# Settings
  UI/apps/admin/public/img/icons/site.webmanifest
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/public/img/icons/site.webmanifest
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
Labels: main, UI

#148 Fix isComplete
  API/CCW.Application.Tests/MapperTests.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Schedule.Tests/AppointmentControllerTests.cs
  API/CCW.Schedule.Tests/CCW.Schedule.Tests.csproj
  API/CCW.Schedule/Controllers/AppointmentController.cs
Labels: main, API

#149 Minor fix + PWA
  UI/apps/admin/public/index.html
  UI/apps/admin/public/manifest.json
  UI/apps/admin/src/registerServiceWorker.js
  UI/apps/public/public/index.html
  UI/apps/public/public/manifest.json
  UI/apps/public/src/registerServiceWorker.js
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/RequestReasonTab.vue
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
Labels: main, UI

#150 AB#2065 updated the info sections with styles
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
Labels: main, UI

#151 AB #1958 Download Documents
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI

#152 AB # cleanup
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/RequestReasonTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
Labels: main, UI

#154 AB#2071 added to the application detail view added continue ability
  API/CCW.Application/Services/CosmosDbService.cs
  UI/apps/public/.eslintrc.json
  UI/libs/core-public/.eslintrc.json
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/.eslintrc.json
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/ui/src/lib/wrappers/FormWrapper.vue
Labels: main, UI, API

#155 add missing word
  API/CCW.Application/Services/CosmosDbService.cs
Labels: main, API

#156 AB#2072 & 2070 updated modify and renew flows
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/stores/applicationTypeStore.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/shared/ui/src/lib/wrappers/FormWrapper.vue
  UI/libs/shared/ui/src/lib/wrappers/RenewFormWrapper.vue
Labels: main, UI

#158 AB#2074 fixed linting
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/FormStepFive.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/FormStepFour.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/FormStepOne.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/FormStepThree.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/FormStepTwo.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepFour.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepOne.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepThree.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepTwo.stories.mdx
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/RenewContactInfoStep.vue
  UI/libs/shared/ui/src/lib/stories/components/form-steps/AddressInfoStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/ApplicationTypeStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/ContactStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/FileUploadStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/IdBirthInfoStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/PersonalInfoStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/PhysicalAppearanceStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/SignatureStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/form-steps/WorkInfoStep.stories.mdx
  UI/libs/shared/ui/src/lib/stories/wrappers/FormWrapper.stories.mdx
  UI/libs/shared/ui/src/lib/wrappers/FormWrapper.vue
  UI/libs/shared/ui/tests/unit/components/form-steps/AddressInfoStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/ApplicationTypeStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/ContactStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/FileUploadStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/IdBirthInfoStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/PersonalInfoStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/PhysicalAppearanceStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/SignatureStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/WorkInfoStep.spec.ts
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/ApplicationTypeStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/ContactStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/FileUploadStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/IdBirthInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/PersonalInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/PhysicalAppearanceStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/form-steps/__snapshots__/WorkInfoStep.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AddressInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AppearanceInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/CitizenInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/ContactInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/DOBinfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/PersonalInfoSection.spec.ts.snap
Labels: main, UI

#159 AB#2074 bug fix loading state on applicationDetailView
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#160 # AB Fix new design changes
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/.storybook/preview-head.html
  UI/libs/core-admin/.storybook/preview.js
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/.storybook/preview-head.html
  UI/libs/core-public/.storybook/preview.js
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/RenewApplicationView.vue
  UI/libs/shared/ui/.storybook/preview-head.html
  UI/libs/shared/ui/.storybook/preview.js
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
  UI/libs/shared/ui/src/lib/composables/useEnvName.ts
  UI/libs/shared/ui/src/lib/plugins/vuetify.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/ui/src/lib/wrappers/FormWrapper.vue
  UI/libs/shared/ui/src/lib/wrappers/RenewFormWrapper.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#163 Booth/add delete to tables
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#164 AB # New design changes
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/CommentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
Labels: main, UI

#165 add footer back
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/SignatureStep.vue
Labels: main, UI

#166 AB # bug fixes
  .gitignore
  .idea/.gitignore
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-pipelines-ui.yml
  Templates/README.MD
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/header/__snapshots__/header.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/permits/__snapshots__/Permits.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI, IaC, API

#168 Booth/UI fixes
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/ui/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
Labels: main, UI
