Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2022-10, with the labels that each got.

#24 Sharath/nx build
  azure-pipelines.yml
Labels: main

#25 UI Pipeline - Nx (Admin | Public)
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#29 Update azure-pipelines-ui.yml for Azure Pipelines
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#30 Update azure-pipelines-ui.yml for Azure Pipelines
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#31 Test UI-Pipeline 1
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  UI/libs/core-public/src/lib/views/About.vue
Labels: main, UI

#32 Update About.vue
  UI/libs/core-public/src/lib/views/About.vue
Labels: main, UI

#34 AB#1727 B2C Login
  .gitignore
  UI/apps/admin/config/dev.config.json
  UI/apps/admin/config/prod.config.json
  UI/apps/admin/config/uat.config.json
  UI/apps/admin/src/main.ts
  UI/apps/public/config/dev.config.json
  UI/apps/public/config/prod.config.json
  UI/apps/public/config/uat.config.json
  UI/apps/public/src/PublicApp.vue
  UI/apps/public/src/main.ts
  UI/libs/core-admin/.storybook/main.js
  UI/libs/core-admin/src/index.ts
  UI/libs/core-admin/src/lib/plugins/query.ts
  UI/libs/core-admin/src/lib/services/index.ts
  UI/libs/core-public/.storybook/main.js
  UI/libs/core-public/src/index.ts
  UI/libs/core-public/src/lib/api/apiTypes.ts
  UI/libs/core-public/src/lib/api/auth/authentication.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/api/interceptors.ts
  UI/libs/core-public/src/lib/components/LoginButton.vue
  UI/libs/core-public/src/lib/plugins/query.ts
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/services/index.ts
  UI/libs/core-public/src/lib/stores/publicAppConfig.ts
  UI/libs/core-public/src/lib/stories/LoginButton.stories.mdx
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/tests/unit/components/LoginButton.spec.ts
  UI/libs/core-public/tests/unit/components/__snapshots__/LoginButton.spec.ts.snap
  UI/libs/shared/ui/.storybook/main.js
  UI/libs/shared/ui/src/lib/components/Button.vue
  UI/libs/shared/ui/src/lib/services/initialize.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#33 Booth/form step 6
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/stores/formStep.ts
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/Button.vue
  UI/libs/shared/ui/src/lib/components/containers/ConfimationSelectionContainer.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/inputs/CheckboxInput.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/stores/alias.ts
  UI/libs/shared/ui/src/lib/stores/physicalAppearance.ts
  UI/libs/shared/ui/src/lib/stores/previousAddress.ts
  UI/libs/shared/ui/src/lib/stories/AddressInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/stories/AliasInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/stories/AppearanceInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/stories/CitizenInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/stories/DOB.stories.ts
  UI/libs/shared/ui/src/lib/stories/IdInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/stories/PersonalInfoSection.stories.ts
  UI/libs/shared/ui/src/lib/types/defaultTypes.ts
  UI/libs/shared/ui/tests/unit/components/PersonalInfoSection.spec.ts
Labels: main, UI

#35 Fix storybook
  UI/libs/core-admin/.storybook/preview.js
  UI/libs/core-public/.storybook/preview.js
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/stories/containers/FormButtonContainer.stories.mdx
  UI/libs/shared/ui/.storybook/preview.js
  UI/libs/shared/ui/src/lib/components/Button.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/stories/AddressInfoSection.stories.ts
  UI/libs/shared/ui/tests/unit/components/PersonalInfoSection.spec.ts
Labels: main, UI

#36 AB#1831 basic landing page created
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/components/Button.vue
  UI/libs/core-public/src/lib/components/acknoledgement-step/AcknowledgementFinal.vue
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/views/About.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/shared/ui/src/index.ts
  UI/libs/shared/ui/src/lib/components/Button.vue
  UI/libs/shared/ui/src/lib/components/containers/AcknowledgementButtonContainer.vue
Labels: main, UI

#38 AB#1855 Basic setup of the acknowledgements completed
  UI/libs/core-public/src/lib/components/acknoledgement-step/AcknowledgementFinal.vue
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementInitial.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stories/AcknowledgementInitial.stories.mdx
  UI/libs/shared/ui/src/lib/stories/AcknowledgementPart.stories.mdx
  UI/libs/shared/ui/tests/unit/components/CheckboxInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/PersonalInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/AcknowledgementInitial.spec.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/AcknowledgementPart.spec.ts
  UI/package.json
Labels: main, UI

#39 AB#1807 completed the second form step and the first section of it.
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/types/defaultTypes.ts
  UI/libs/shared/utils/src/lib/lists/defaultList.ts
Labels: main, UI

#41 UI pipeline final deployment
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#42 AB#1852 update text fields and created next step
  UI/README_FILETREE.MD
  UI/libs/core-admin/src/lib/components/brand/BrandTitle.vue
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandTitle.spec.ts.snap
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepTwo.vue
  UI/libs/core-public/tests/unit/components/containers/__snapshots__/FormButtonContainer.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DocumentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/inputs/RadioGroupInput.vue
  UI/libs/shared/ui/src/lib/components/inputs/TextInput.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/DOB.ts
  UI/libs/shared/ui/src/lib/stores/alias.ts
  UI/libs/shared/ui/src/lib/stores/citizenship.ts
  UI/libs/shared/ui/src/lib/stores/contact.ts
  UI/libs/shared/ui/src/lib/stores/id.ts
  UI/libs/shared/ui/src/lib/stores/physicalAppearance.ts
  UI/libs/shared/ui/src/lib/stores/previousAddress.ts
  UI/libs/shared/ui/tests/unit/components/TextInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/TextInput.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package.json
Labels: main, UI

#43 AB#1726 Renew token, App structure, Loading state & misc
  .gitignore
  UI/README_FILETREE.MD
  UI/apps/admin/configure-webpack.js
  UI/apps/admin/src/AdminApp.vue
  UI/apps/admin/src/main.ts
  UI/apps/public/configure-webpack.js
  UI/apps/public/src/PublicApp.vue
  UI/apps/public/src/main.ts
  UI/jest.setup.ts
  UI/libs/core-admin/jest.setup.ts
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navbar/NavBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/tests/unit/components/login/LoginButton.spec.ts
  UI/libs/core-admin/tests/unit/components/login/__snapshots__/LoginButton.spec.ts.snap
  UI/libs/core-public/jest.setup.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/tests/unit/components/login/LoginButton.spec.ts
  UI/libs/core-public/tests/unit/components/login/__snapshots__/LoginButton.spec.ts.snap
  UI/libs/shared/ui/configure-webpack.js
  UI/libs/shared/ui/jest.setup.ts
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementInitial.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
  UI/libs/shared/ui/src/lib/composables/useInterval.ts
  UI/libs/shared/ui/src/lib/plugins/vuetify.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/AcknowledgementInitial.spec.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/AcknowledgementPart.spec.ts
  UI/libs/shared/ui/tests/unit/components/__snapshots__/PersonalInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/__snapshots__/__snapshots__/AcknowledgementInitial.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/__snapshots__/__snapshots__/AcknowledgementPart.spec.ts.snap
  UI/libs/shared/utils/jest.setup.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#44 AB#1863 Created AAD SP Scripts for CCW
  Deployment/Scripts/AAD-Authentication/ClaimsManifest.json
  Deployment/Scripts/AAD-Authentication/GraphPolicyManifest.json
  Deployment/Scripts/AAD-Authentication/New-AADGroup.psm1
  Deployment/Scripts/AAD-Authentication/New-AppRegistration.psm1
  Deployment/Scripts/AAD-Authentication/New-AuthenticationScheme.ps1
  Deployment/Scripts/AAD-Authentication/New-RBACRoleAssignment.psm1
  Deployment/Scripts/AAD-Authentication/OAuthPermissions.json
  Deployment/Scripts/AAD-Authentication/RolesManifest.json
  Deployment/Scripts/AAD-Authentication/Sample-Script.ps1
  Deployment/Scripts/AAD-Authentication/SpaRedirectUrl.json
Labels: main, IaC

#45 AB#1750 - Brand template form
  .gitignore
  UI/apps/admin/configure-webpack.js
  UI/apps/public/configure-webpack.js
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/BrandLogo.vue
  UI/libs/core-admin/src/lib/components/brand/BrandTitle.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stores/brand.ts
  UI/libs/core-admin/src/lib/stories/components/brand/BrandForm.stories.mdx
  UI/libs/core-admin/src/lib/stories/components/brand/BrandLogo.stories.mdx
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/tests/unit/components/brand/BrandForm.spec.ts
  UI/libs/core-admin/tests/unit/components/brand/BrandLogo.spec.ts
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandLogo.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandTitle.spec.ts.snap
  UI/libs/shared/ui/configure-webpack.js
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/components/inputs/FileInput.vue
  UI/libs/shared/ui/src/lib/stories/FileInput.stories.ts
Labels: main, UI

#46 Updated nx condition to UI pipeline
  .gitignore
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#48 AB#1853 Added the third step for the 2nd part of the form
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepOne.stories.mdx
  UI/libs/core-public/tests/unit/components/form-steps/SecondFormStepOne.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationInfoSection.vue
  UI/libs/shared/ui/src/lib/components/inputs/RadioGroupInput.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/previousAddress.ts
  UI/libs/shared/ui/src/lib/stores/weapons.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#50 Agency profile settings add get and create
  API/CCW.Admin/CCW.Admin.csproj
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Admin/Controllers/WeatherForecastController.cs
  API/CCW.Admin/Models/AgencyProfileRequestModel.cs
  API/CCW.Admin/Models/AgencyProfileSettings.cs
  API/CCW.Admin/Program.cs
  API/CCW.Admin/Properties/launchSettings.json
  API/CCW.Admin/Services/CosmosDbService.cs
  API/CCW.Admin/Services/ICosmosDbService.cs
  API/CCW.Admin/WeatherForecast.cs
  API/CCW.Admin/appsettings.json
  API/CCW.Application/appsettings.json
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Models/UserProfileRequestModel.cs
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/CosmosDbService.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
  API/CCW.UserProfile/appsettings.json
Labels: main, API

#51 AB#1854 Added the different mailing address
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/stores/differentMailing.ts
  UI/libs/shared/ui/src/lib/stores/mailingAddress.ts
Labels: main, UI

#52 Fix get admin settings
  API/CCW.Admin/Services/CosmosDbService.cs
Labels: main, API

#55 AB#1867 Fix Error loading state
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-public/.storybook/main.js
  UI/libs/core-public/.storybook/preview.js
  UI/libs/core-public/src/lib/plugins/vuetify.ts
Labels: main, UI

#56 AB#1871 created the api calls and store for the complete application
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/plugins/query.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/plugins/query.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/FormView.vue
  UI/libs/core-public/tests/unit/components/form-steps/FormStepTwo.spec.ts
  UI/libs/shared/ui/src/lib/stores/personalInfo.ts
  UI/libs/shared/ui/tests/unit/components/AddressTable.spec.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package.json
Labels: main, UI

#57 AB#1806 Fix settings API controller
  API/CCW.Admin/Services/CosmosDbService.cs
Labels: main, API

#58 AB#1867 User Profile, Route Guards, Navigation, Landing Page, Logout and Persistence
  UI/apps/admin/src/AdminApp.vue
  UI/jest.setup.ts
  UI/libs/core-admin/jest.setup.ts
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stores/adminAppConfig.ts
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/tests/unit/components/brand/BrandForm.spec.ts
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-public/.storybook/preview.js
  UI/libs/core-public/jest.setup.ts
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/stores/publicAppConfig.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/jest.setup.ts
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/plugins/vuetify.ts
  UI/libs/shared/ui/src/lib/stores/appConfig.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/ui/src/lib/stores/index.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#61 Booth/save from form
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/FormStepFive.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/FormStepFour.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/FormStepThree.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/SeconFormStepTwo.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/SecondFormStepThree.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SeconFormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepThree.spec.ts.snap
  UI/libs/shared/ui/src/lib/stores/DOB.ts
  UI/libs/shared/ui/src/lib/stores/alias.ts
  UI/libs/shared/ui/src/lib/stores/application.ts
  UI/libs/shared/ui/src/lib/stores/citizenship.ts
  UI/libs/shared/ui/src/lib/stores/contact.ts
  UI/libs/shared/ui/src/lib/stores/currentAddress.ts
  UI/libs/shared/ui/src/lib/stores/differentMailing.ts
  UI/libs/shared/ui/src/lib/stores/employment.ts
  UI/libs/shared/ui/src/lib/stores/id.ts
  UI/libs/shared/ui/src/lib/stores/mailingAddress.ts
  UI/libs/shared/ui/src/lib/stores/personalInfo.ts
  UI/libs/shared/ui/src/lib/stores/physicalAppearance.ts
  UI/libs/shared/ui/src/lib/stores/previousAddress.ts
  UI/libs/shared/ui/src/lib/stores/user.ts
  UI/libs/shared/ui/src/lib/stores/weapons.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#63 AB#1796 - 404 route handling
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/views/NotFound.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/core-public/src/lib/views/NotFound.vue
Labels: main, UI

#64 AB#1879 some clean up for demo
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#65 Brand Template cleanup
  API/CCW.Admin/Services/CosmosDbService.cs
  API/CCW.sln
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/stores/brandStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/Home.vue
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepSix.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepThree.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepThree.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepTwo.stories.mdx
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/Home.vue
Labels: main, UI, API

#66 Booth/update api
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#60 Azure-pipelines
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#68 AB#1876 - fix storybook build failures
  UI/libs/core-admin/.storybook/main.js
  UI/libs/core-admin/.storybook/preview.js
  UI/libs/core-public/.storybook/main.js
  UI/libs/core-public/.storybook/preview.js
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/.storybook/main.js
  UI/libs/shared/ui/.storybook/preview.js
Labels: main, UI

#69 commented
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#71 comment publish
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#72 Booth/add missing fields
  UI/.eslintrc.json
  UI/.gitignore
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/FormStepTwo.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#73 Booth/add discharge disclaimer
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#74 AB#1917 - Agency Authentication Validation
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stories/components/brand/BrandForm.stories.mdx
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-public/src/lib/components/containers/SecondFormContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/utils/src/lib/types/Item.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/libs/shared/utils/src/lib/utils.ts
Labels: main, UI

#76 AB#1861 Created draft architecture document
  Documentation/Architecture/CSSA-CCW High Level Architecture.pdf
  Documentation/Architecture/CSSA-CCW High Level Architecture.png
  Documentation/Architecture/CSSA-CCW High Level Architecture.vsdx
  Documentation/Architecture/README.md
Labels: Documentation, main

#75 Storybook - combine admin/public for gh-pages
  .github/workflows/storybook.yml
  UI/libs/core-admin/src/lib/stories/components/brand/BrandForm.stories.mdx
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/shared/ui/.storybook/main.js
Labels: main, UI

#77 Booth/add different spouse address
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#78 AB#1900 Add the employer information to the application
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#80 AB#1924 Create the new form for the renewal application
  UI/libs/core-public/src/lib/components/containers/RenewFormContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/RenewFormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewFormStepOne.vue
  UI/libs/core-public/src/lib/components/wrappers/RenewFormWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/views/RenewFormView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#81 Booth/api update
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#82 Ofelia/storage document
  API/CCW.Document/CCW.Document.csproj
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Upload/files/637998067282988172.xlsx
  API/CCW.Document/Upload/files/637998068296534041.xlsx
  API/CCW.Document/appsettings.json
Labels: main, API

#84 Booth/test updates
  UI/libs/core-public/src/lib/stories/containers/AcknowledgementContainer.stories.mdx
  UI/libs/core-public/tests/unit/components/containers/AcknowledgementContainer.spec.ts
  UI/libs/core-public/tests/unit/components/containers/__snapshots__/AcknowledgementContainer.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/stories/AcknowledgementButtonConatainer.stories.mdx
  UI/libs/shared/ui/tests/unit/components/acknowledgements/AcknowledgementInitial.spec.ts
  UI/libs/shared/ui/tests/unit/components/acknowledgements/AcknowledgementPart.spec.ts
  UI/libs/shared/ui/tests/unit/components/acknowledgements/__snapshots__/AcknowledgementInitial.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/acknowledgements/__snapshots__/AcknowledgementPart.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/alerts/FormErrorAlert.spec.ts
  UI/libs/shared/ui/tests/unit/components/alerts/__snapshots__/FormErrorAlert.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/containers/AcknowledgementButtonContainer.spec.ts
  UI/libs/shared/ui/tests/unit/components/containers/__snapshots__/AcknowledgementButtonContainer.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/AddressInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/AliasInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/AppearanceInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/CitizenInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/ContactInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/DOBinfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/PersonalInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AddressInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AliasInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/AppearanceInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/CitizenInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/ContactInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/DOBinfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/__snapshots__/PersonalInfoSection.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/inputs/CheckboxInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/inputs/RadioGroupInput.spec.ts
  UI/libs/shared/ui/tests/unit/components/inputs/__snapshots__/CheckboxInput.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/inputs/__snapshots__/RadioGroupInput.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/AddressTable.spec.ts
  UI/libs/shared/ui/tests/unit/components/tables/AliasTable.spec.ts
  UI/libs/shared/ui/tests/unit/components/tables/WeaponsTable.spec.ts
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AddressTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/AliasTable.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/WeaponsTable.spec.ts.snap
  UI/package.json
Labels: main, UI

#85 Booth/pii shield
  UI/libs/core-public/.eslintrc.json
  UI/libs/core-public/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFour.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepOne.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepThree.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepOne.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/AliasDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/FormStepTwo.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFour.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepOne.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepThree.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepOne.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/ui/tests/unit/components/tables/__snapshots__/WeaponsTable.spec.ts.snap
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/libs/shared/utils/tests/formatters/defaultFormatters.spec.ts
  UI/package.json
Labels: main, UI

#87 Booth/signature step
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepTwo.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SecondFormStepFour.vue
  UI/libs/core-public/src/lib/components/wrappers/SecondFormWrapper.vue
  UI/libs/core-public/src/lib/senders/documentSenders.ts
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepFour.stories.mdx
  UI/libs/core-public/src/lib/stories/form-stepper/form-steps/SecondFormStepTwo.stories.mdx
  UI/libs/core-public/tests/unit/components/form-steps/SecondFormStepFour.spec.ts
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SecondFormStepFour.spec.ts.snap
  UI/libs/shared/ui/tests/unit/components/info-sections/DOBinfoSection.spec.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#89 Booth/payment
  UI/libs/core-public/src/lib/components/containers/FinalizeContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/wrappers/PaymentWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/stores/brandStore.ts
  UI/libs/core-public/src/lib/stores/completeApplication.ts
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#92 Booth/appointment schedule
  API/CCW.Admin/Properties/launchSettings.json
  API/CCW.Application/Properties/launchSettings.json
  API/CCW.Document/Properties/launchSettings.json
  API/CCW.Payment/Properties/launchSettings.json
  API/CCW.Schedule/Properties/launchSettings.json
  API/CCW.UserProfile/Properties/launchSettings.json
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FormStepFive.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepFive.spec.ts.snap
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#93 Add upload appointments from csv file
  API/CCW.Schedule/CCW.Schedule.csproj
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Models/AppointmentUploadModel.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  API/CCW.Schedule/Services/ICosmosDbService.cs
Labels: main, API

#94 AB#1901 - Appointment Design, Dark Mode, PWA Connection Status
  UI/.eslintrc.json
  UI/apps/admin/src/AdminApp.vue
  UI/apps/admin/src/main.ts
  UI/libs/core-admin/src/lib/components/appointment/AppointmentScheduler.vue
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/views/Home.vue
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/AppointmentScheduler.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/header/__snapshots__/header.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
  UI/libs/shared/ui/src/lib/components/status/ConnectionStatus.vue
  UI/libs/shared/ui/src/lib/stores/appConfig.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/ui/src/lib/stores/statusStore.ts
  UI/libs/shared/ui/src/lib/stores/themeStore.ts
  UI/libs/shared/ui/src/lib/stories/components/mode/ThemeMode.stories.mdx
  UI/libs/shared/ui/src/lib/stories/components/status/ConnectionStatus.stories.mdx
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#95 Booth/update landing
  UI/apps/public/public/img/icons/agency_logo.svg
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/views/Home.vue
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#96 Booth/create more info
  UI/libs/core-public/src/lib/components/containers/MoreInformationConatainer.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/components/navbar/SideBar.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/stores/appInfoStepStore.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/MoreInformationView.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/FormStepTwo.spec.ts.snap
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI
