Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-09, with the labels that each got.

#519 Bug/2812 fix qq formatting
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
Labels: main, UI

#521 Remove interval
  UI/apps/admin/src/AdminApp.vue
  UI/libs/shared/ui/src/lib/api/Interval.vue
Labels: main, UI

#520 Update dialog buttons
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/appointment/DateTimePicker.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/dialogs/AppointmentDeleteDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
Labels: main, UI

#522 bug: fix debug blobclientoptions again and file naming
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/Services/AzureStorage.cs
Labels: main, API

#523 feat: add validation to agreements
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
Labels: main, UI

#524 Feature/2568 holiday management
  API/CCW.Schedule/CCW.Schedule.csproj
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Entities/AppointmentManagement.cs
  API/CCW.Schedule/Entities/OrganizationHolidays.cs
  API/CCW.Schedule/Models/AppointmentManagementRequestModel.cs
  API/CCW.Schedule/Models/HolidaysResponseModel.cs
  API/CCW.Schedule/Models/OrganizationHolidaysRequestModel.cs
  API/CCW.Schedule/Program.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  API/CCW.Schedule/Services/ICosmosDbService.cs
  API/CCW.Schedule/appsettings.Development.json
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentManagement.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
  UI/libs/core-admin/src/lib/components/templates/HolidayManagement.vue
  UI/libs/core-admin/src/lib/views/AppointmentManagementView.vue
  UI/libs/core-admin/tsconfig.json
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#526 fix: update time zone offset for break start time
  API/CCW.Schedule/Services/CosmosDbService.cs
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
Labels: main, UI, API

#529 fix: move todays appointments out of state and filter on the fly
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
Labels: main, UI

#532 fix: update stepper headers to move below on smaller breakpoints.
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#533 feat: update dialog action buttons
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/dialogs/ApprovedEmailApplicantDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/RevokeCancelDeniedDialog.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentManagement.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
Labels: main, UI

#534 feat: add widowed and divorced options
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
Labels: main, UI

#536 fix: check for null organizational holidays before returning result
  API/CCW.Schedule/Services/CosmosDbService.cs
Labels: main, API

#538 Bug/2861 application pdf
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#535 task: add reason for name change field
  API/CCW.Application/Entities/Alias.cs
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#537 task: add reason for different spouse address
  API/CCW.Application/Entities/SpouseAddressInformation.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#540 bug: fix caliber typo & duplicate ruleset
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
Labels: main, UI
