Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-06, with the labels that each got.

#403 Move date of birth information to personal step
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#404 Add admonishment for immigrant alien
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#405 Update defaultFormatters.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
Labels: main, UI

#406 Task/2588 remove country dropdown
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
Labels: main, UI

#407 Fix step indexing on mobile view
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#408 Add missing & remove unused application statuses
  API/CCW.Application/Enum/ApplicationStatus.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
Labels: main, UI, API

#409 Make date fields typed as well as calendar input
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#410 Update FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#411 Feature/2618 appointment table
  API/CCW.Admin/Properties/launchSettings.json
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/SummarizedPermitApplication.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Program.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Common/Models/AppointmentStatus.cs
  API/CCW.Document/Properties/launchSettings.json
  API/CCW.Payment/Properties/launchSettings.json
  API/CCW.Schedule/Clients/ApplicationServiceClient.cs
  API/CCW.Schedule/Clients/IApplicationServiceClient.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Entities/AppointmentWindow.cs
  API/CCW.Schedule/Models/AppointmentWindowRequestModel.cs
  API/CCW.Schedule/Models/AppointmentWindowResponseModel.cs
  API/CCW.Schedule/Models/AppointmentWindowUpdateRequestModel.cs
  API/CCW.Schedule/Program.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  API/CCW.Schedule/appsettings.Development.json
  API/CCW.UserProfile/Properties/launchSettings.json
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/dialogs/AppointmentDeleteDialog.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/.eslintrc.json
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#412 Feature/2509 customer reschedule
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  UI/.eslintrc.json
  UI/apps/admin/.eslintrc.json
  UI/apps/public/.eslintrc.json
  UI/libs/core-admin/.eslintrc.json
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-public/.eslintrc.json
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/.eslintrc.json
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/components/dialogs/DeleteDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationTypeInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#415 Bug/2635 finalize page loading twice
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
Labels: main, UI

#416 feat: add validation to qualifying questions
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
Labels: main, UI

#414 Feat: add validation for reschedule and cancel button
  UI/libs/core-public/src/lib/components/containers/ApplicationStatusContainer.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#417 Feature/2610 admin comments
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/Comment.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Mappers/RequestUserPermitApplicationModelToEntityMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Program.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/CommentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#420 Task/2637 move appointment alert
  UI/libs/core-public/src/lib/views/FinalizeView.vue
Labels: main, UI

#419 feat: update icon colors
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
Labels: main, UI

#418 feat: update responsiveness of application detail view, improve histo…
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
Labels: main, UI

#421 Fix: add phone validation for employer
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
Labels: main, UI

#424 bug: fix scrolling into each tab
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#425 bug: fix middle initial null
  API/CCW.Application/Controllers/PermitApplicationController.cs
Labels: main, API

#422 feat: add hamburger menu to hidden navigation drawer
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
Labels: main, UI

#426 feat: add cost to application at time of creation
  API/CCW.Admin/Entities/AgencyProfileSettings.cs
  API/CCW.Admin/Entities/Cost.cs
  API/CCW.Admin/Entities/CostType.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToUserApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Common/CCW.Common.csproj
  API/CCW.Common/Models/Cost.cs
  API/CCW.Common/Models/CostType.cs
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#427 Bug/newton soft updated version
  API/CCW.Admin/CCW.Admin.csproj
  API/CCW.Admin/Mappers/AgencyProfileRequestSettingsModelToEntityMapper.cs
  API/CCW.Admin/Mappers/EntityToAgencyProfileSettingsResponseModelMapper.cs
  API/CCW.Admin/Models/AgencyProfileSettingsRequestModel.cs
  API/CCW.Admin/Models/AgencyProfileSettingsResponseModel.cs
Labels: main, API

#429 fix: typo
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#430 fix: move submitted to licensing date time to front end
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.UserProfile/CCW.UserProfile.csproj
  API/CCW.UserProfile/Program.cs
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#431 fix: initialize empty array instead of null
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/CommentsTab.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI, API

#432 Feature/2623 assign licensing employee
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/SummarizedPermitApplication.cs
  API/CCW.Application/Mappers/EntityToSummarizedPermitApplicationModelMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.UserProfile/Controllers/AdminUserController.cs
  API/CCW.UserProfile/Entities/AdminUser.cs
  API/CCW.UserProfile/Mappers/AdminUserProfileRequestModelToEntityMapper.cs
  API/CCW.UserProfile/Mappers/AllAdminUsersToAdminUserProfileResponseModelMapper.cs
  API/CCW.UserProfile/Mappers/EntityToAdminUserProfileResponseModelMapper.cs
  API/CCW.UserProfile/Models/AdminUserProfileRequestModel.cs
  API/CCW.UserProfile/Models/AdminUserProfileResponseModel.cs
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/CosmosDbService.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
  API/CCW.UserProfile/appsettings.Development.json
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/stores/adminUserStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#433 fix: add condition to display of assigned applications card
  UI/libs/core-admin/src/lib/views/HomeView.vue
Labels: main, UI
