Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-08, with the labels that each got.

#446 Feature/2582 public loading rework
  UI/apps/public/src/Loader.vue
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-public/src/lib/api/interceptors.ts
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#448 Task/2706 color code flags
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#449 feat: add option for starting 90 day countdown at submission date
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#451 feat: add azurite storage emulator
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Services/AzureStorage.cs
  API/CCW.Document/Services/IAzureStorage.cs
  API/CCW.Document/appsettings.Development.json
Labels: main, API

#450 Bug/2705 fix dialog boxes
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#453 fix: update instantiation of program.cs to allow local connection
  API/CCW.Admin/Program.cs
  API/CCW.Application/Program.cs
  API/CCW.Schedule/Program.cs
  API/CCW.UserProfile/Program.cs
Labels: main, API

#454 fix: add emulator connection string
  API/CCW.Admin/appsettings.Development.json
Labels: main, API

#452 Task/2709 set pre flagged status
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/SummarizedPermitApplication.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#455 fix: update the way the user photo is retrieved
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
Labels: main, UI

#456 Bug/2710 user portrait
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
Labels: main, UI

#457 Bug/2710 user portrait
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
Labels: main, UI

#459 fix: update queries on admin load
  UI/apps/admin/src/AdminApp.vue
Labels: main, UI

#460 fix: add user portrait endpoint
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, API

#462 feat: disable continue button for certain application statuses
  API/CCW.Application/Enum/ApplicationStatus.cs
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#463 feat: update logic for user reschedule when they no show for appointment
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Enum/ApplicationStatus.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/stores/paymentStore.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#464 Feat/2687 ability to delete documents and edit names
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/UploadedDocument.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Services/AzureStorage.cs
  API/CCW.Document/Services/IAzureStorage.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, API

#465 feat: add assignedTo to application table and remove email and payment
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#466 Update AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
Labels: main, UI

#467 feat: add pause and reactivate 90 day countdowns
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UserApplication.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#468 feat: allow user to reschedule and resubmit if they withdraw
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#469 Feature/2679 cancel rework
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationTypeInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
Labels: main, UI

#470 feat: remove status progress bar for now
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#471 feat: update color step for dark mode and light mode
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
Labels: main, UI

#472 Feature/2685 contingent deny
  API/CCW.Application/Enum/ApplicationStatus.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#473 Feature/2717 upload documents until approved
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#474 fix: get application again on application detail page reload
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#475 fix: show reschedule button if user no-shows
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#476 add button validation for suspend, denied, and revoke
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
Labels: main, UI

#478 Update FinalizeView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
Labels: main, UI

#479 Feature/2515 dashboard page
  API/CCW.Application/Entities/QualifyingQuestions.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Entities/AppointmentWindow.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  API/CCW.Schedule/Services/ICosmosDbService.cs
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/cards/ActiveLicensesCard.vue
  UI/libs/core-admin/src/lib/components/cards/AssignedApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/DeniedApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/NewAppointmentsCard.vue
  UI/libs/core-admin/src/lib/components/cards/NextAvailableAppointmentCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingJudicalApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingReserveApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingStandardApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#480 bug/2658 partial social is broken
  API/CCW.Application/Services/CosmosDbService.cs
Labels: main, API

#477 Feat/2692 appointment complete removes reschedule and cancel buttons
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#482 fix: prevent duplicate appointments
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#481 bug/2652 if application is marked "ready for appointment" you can continue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#484 Bug/2765 save and continue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
Labels: main, UI

#485 bug fix- first name allows space
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
Labels: main, UI

#486 Task/2674 require judicial reserve documents
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#487 fix logic in removing application appointment variables
  API/CCW.Schedule/Controllers/AppointmentController.cs
Labels: main, API

#488 fix: Correct date's not matching
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#489 fix- number of new appointments and reschedules
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Entities/AppointmentWindow.cs
  API/CCW.Schedule/Models/AppointmentWindowCreateRequestModel.cs
  API/CCW.Schedule/Models/AppointmentWindowResponseModel.cs
  API/CCW.Schedule/Models/AppointmentWindowUpdateRequestModel.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#490 fix: alias flag not saving
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#492 feat/2770 capitalize Sheriff's Department
  UI/libs/core-public/src/lib/views/RecieptView.vue
Labels: main, UI

#493 change z-index for comments tab
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
Labels: main, UI

#494 Bug/2777 refresh while filling out application breaks page
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#495 add emailApplicantDialog for approved status
  API/CCW.Application/Enum/ApplicationStatus.cs
  UI/libs/core-admin/src/lib/components/dialogs/ApprovedEmailApplicantDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#496 Bug/2785 require military status
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#497 Feature/2774 mobile responsive
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Schedule/Services/CosmosDbService.cs
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/cards/NewAppointmentsCard.vue
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/GeneralInfoWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/PaymentWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/PriceInfoWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/views/Loader.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementInitial.vue
  UI/libs/shared/ui/src/lib/components/acknowledgement-section/AcknowledgementPart.vue
  UI/libs/shared/ui/src/lib/components/containers/AcknowledgementButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
Labels: main, UI, API

#499 Bug/2767 saved appointment times
  API/CCW.Schedule/Services/CosmosDbService.cs
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#500 Task/2789 modify creation logic
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#501 fix: add validation to cards
  UI/libs/core-admin/src/lib/components/cards/PendingJudicalApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingReserveApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingStandardApplicationsCard.vue
Labels: main, UI

#498 feat/2790-add-acknowledgement forms to final page
  API/CCW.Application/Clients/DocumentServiceClient.cs
  API/CCW.Application/Clients/IDocumentServiceClient.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Agreements.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#506 Feat/add agreements to final page
  API/CCW.Application/Clients/DocumentServiceClient.cs
  API/CCW.Application/Clients/IDocumentServiceClient.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Agreements.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#507 feat: add eight hour safety course document and dialog
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#508 Task/2675 validate question two
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/QualifyingQuestions.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#505 feat: add expired application renewal period and archived application…
  API/CCW.Admin/Entities/AgencyProfileSettings.cs
  API/CCW.Admin/Models/AgencyProfileSettingsRequestModel.cs
  API/CCW.Admin/Models/AgencyProfileSettingsResponseModel.cs
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#509 feat: improve file upload step
  API/CCW.Application/Entities/Agreements.cs
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI, API

#510 Bug/2538 add ssn validation
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#513 Text cleanup
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#514 Task/2747 improve application table
  API/CCW.Application/Services/CosmosDbService.cs
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI, API

#515 feat: update logo endpoints
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
Labels: main, UI, API

#517 Change modification functionality
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#516 Feat/2517 add revocation letter to admin
  API/CCW.Application/Clients/DocumentServiceClient.cs
  API/CCW.Application/Clients/IDocumentServiceClient.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/AdminUser.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Enum/ApplicationStatus.cs
  API/CCW.Application/Models/AgencyProfileSettingsModel.cs
  API/CCW.Application/Program.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.UserProfile/Entities/AdminUser.cs
  API/CCW.UserProfile/Models/AdminUserProfileRequestModel.cs
  API/CCW.UserProfile/Models/AdminUserProfileResponseModel.cs
  UI/libs/core-admin/src/lib/components/dialogs/RevokeCancelDeniedDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#518 fix: update query for getting user applications, add interval
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/Interval.vue
Labels: main, UI
