Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-03, with the labels that each got.

#334 Feature/2472 admin user settings
  API/CCW.Application/Mappers/PermitApplicationToUploadDocumentMapper.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Document/Services/AzureStorage.cs
  API/CCW.Document/Services/IAzureStorage.cs
  API/CCW.Document/appsettings.Development.json
  API/CCW.UserProfile/Controllers/AdminUserController.cs
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Entities/AdminUser.cs
  API/CCW.UserProfile/Entities/UploadedDocument.cs
  API/CCW.UserProfile/Mappers/AdminUserProfileRequestModelToEntityMapper.cs
  API/CCW.UserProfile/Mappers/EntityToAdminUserProfileResponseModelMapper.cs
  API/CCW.UserProfile/Models/AdminUserProfileRequestModel.cs
  API/CCW.UserProfile/Models/AdminUserProfileResponseModel.cs
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/CosmosDbService.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
  API/CCW.UserProfile/appsettings.Development.json
  Deployment/IaC/Marketplace/mainTemplate.json
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-public/src/lib/api/interceptors.ts
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/ui/src/lib/stores/index.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI, IaC, API

#336 fix(Header.vue): show admin user profile dialog if admin user doesn't…
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
Labels: main, UI

#337 Booth/reschedule issues
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#339 fixing rebasing issue.
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
Labels: main, UI

#340 Feature/update sidebar
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/header/__snapshots__/header.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
Labels: main, UI

#342 Bug/2474 application details refresh
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/shared/ui/src/lib/components/footer/Footer.vue
  UI/libs/shared/ui/src/lib/stores/index.ts
Labels: main, UI

#343 Bug/2475 saving admin user
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/stores/adminUserStore.ts
  UI/libs/shared/ui/src/lib/stores/auth.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#345 Feature/2478 remove good cause
  UI/libs/core-public/src/lib/components/containers/MoreInformationConatainer.vue
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#348 Updated no photo with an actual photo.
  UI/apps/admin/public/img/icons/no-photo.png
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#349 Updated reschedule snackbar
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
Labels: main, UI

#351 Fixed pip variable values from $result
  Deployment/IaC/Infrastructure/Agency-Firewall-Pip/deploy-agency-pip.ps1
Labels: main, IaC

#353 Booth/question one fix
  API/CCW.Application/Mappers/PermitApplicationToQualifyingQuestionsMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationToQualifyingQuestionsMapper.cs
  API/CCW.Application/Mappers/UserRequestPermitApplicationToQualifyingQuestionsMapper.cs
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#354 Update deploy-agency-pip.ps1
  Deployment/IaC/Infrastructure/Agency-Firewall-Pip/deploy-agency-pip.ps1
Labels: main, IaC
