Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-01, with the labels that each got.

#245 AB#2227 fixes for 2191 2227
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/MoreInformationConatainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/MoreInformationView.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
Labels: main, UI

#246 fix to light theme navbar
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
Labels: main, UI

#248 Ofelia/jwt changes
  API/CCW.Application.Tests/CosmosDbServiceTests.cs
  API/CCW.Application.Tests/PermitApplicationControllerTests.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/SummarizedPermitApplication.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Enum/PaymentStatus.cs
  API/CCW.Application/Mappers/EntityToSummarizedPermitApplicationModelMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToUserApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Models/PermitApplicationResponseModel.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.UserProfile.Tests/MapperTests.cs
  API/CCW.UserProfile.Tests/UserControllerTests.cs
  API/CCW.UserProfile/Controllers/UserController.cs
  API/CCW.UserProfile/Entities/Email.cs
  API/CCW.UserProfile/Entities/User.cs
  API/CCW.UserProfile/Mappers/EntityToUserProfileResponseModelMapper.cs
  API/CCW.UserProfile/Mappers/IMapper.cs
  API/CCW.UserProfile/Mappers/UserProfileRequestModelToEntityMapper.cs
  API/CCW.UserProfile/Models/UserProfileResponseModel.cs
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/Services/CosmosDbService.cs
  API/CCW.UserProfile/Services/ICosmosDbService.cs
Labels: main, API

#249 userId partionkey fix, bring outside
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/PermitApplication.cs
  API/CCW.Application/Entities/SpouseAddressInformation.cs
  API/CCW.Application/Entities/SpouseInformation.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Mappers/EntityToPermitApplicationResponseMapper.cs
  API/CCW.Application/Mappers/EntityToUserPermitApplicationResponseMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitApplicationToUserApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/RequestPermitApplicationModelToEntityMapper.cs
  API/CCW.Application/Mappers/RequestUserPermitApplicationModelToEntityMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Models/PermitApplicationRequestModel.cs
  API/CCW.Application/Models/PermitApplicationResponseModel.cs
  API/CCW.Application/Models/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Application/Models/UserPermitApplicationRequestModel.cs
  API/CCW.Application/Models/UserPermitApplicationResponseModel.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#250 Booth/addings loadings
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/views/ApplicationView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#251 userid for update app
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Document/CCW.Document.csproj
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#252 #2253 #2268 - Appointment link and App Version
  Deployment/Pipelines/azure-pipelines-ui.yml
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/footer/Footer.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/tests/unit/components/appointment/__snapshots__/Appointments.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/footer/Footer.spec.ts
  UI/libs/core-admin/tests/unit/components/footer/__snapshots__/Footer.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/permits/__snapshots__/Permits.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
  UI/libs/core-public/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/AliasDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/dialogs/__snapshots__/PreviousAddressDialog.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/AddressInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/PersonalInfoStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/SignatureStep.spec.ts.snap
  UI/libs/core-public/tests/unit/components/form-steps/__snapshots__/WorkInfoStep.spec.ts.snap
  UI/libs/shared/ui/src/lib/components/footer/Footer.vue
  UI/libs/shared/utils/src/lib/version.js
Labels: main, UI, IaC

#253 Version change fix
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#254 AB#2261 updated fixes for loading and appointments
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ContactStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PhysicalAppearanceStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewContactInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/QualifyingQuestionsView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
Labels: main, UI

#255 AB#2270 fix the button spacing.
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
Labels: main, UI

#256 Change name of service connection
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-pipelines-ui.yml
  Deployment/Pipelines/templates/dev-002-vars.yml
  Deployment/Pipelines/templates/dev-003-vars.yml
Labels: main, IaC, API

#257 Fix build version
  UI/libs/shared/ui/src/lib/components/footer/Footer.vue
Labels: main, UI

#258 Update userId for applications. Add delete application for a AAD user…
  API/CCW.Application.Tests/CosmosDbServiceTests.cs
  API/CCW.Application.Tests/PermitApplicationControllerTests.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#259 update the api changes
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI

#260 AB#2262 updated the calendar
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
Labels: main, UI

#261 Ofelia/update tests
  API/CCW.Application.Tests/CosmosDbServiceTests.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#262 Fix Documents
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI

#263 Sharath/document - 2120, 2230, 2199, 2247
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
Labels: main, UI

#265 Add history on create app. Return base64 for images. Sort getAll. Upd…
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Mappers/RequestUserPermitApplicationModelToEntityMapper.cs
  API/CCW.Application/Services/CosmosDbService.cs
  API/CCW.Application/Services/ICosmosDbService.cs
  API/CCW.Document/Controllers/DocumentController.cs
Labels: main, API

#264 typo
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#266 #2180 view Ready to review applications first
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#267 AB#2282 Api call updates, SSN and Stepper updates.
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationStatus.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/package-lock.json
  package.json
Labels: main, UI

#268 AB#2282 Api call updates, SSN and Stepper updates.
  package.json
Labels: main

#269 fix pipeline
  UI/package-lock.json
Labels: main, UI

#270 #2277 - fix immigration info
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
Labels: main, UI

#271 #2201 - Sheriff Signature
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#272 Sketch application print
  API/CCW.Application.Tests/PermitApplicationControllerTests.cs
  API/CCW.Application/CCW.Application.csproj
  API/CCW.Application/Clients/DocumentServiceClient.cs
  API/CCW.Application/Clients/IDocumentServiceClient.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/PdfFiles/Application_Template.pdf
  API/CCW.Application/PdfFiles/Permit_Template.pdf
  API/CCW.Application/PdfFiles/sheriffMartinezSigBlack.JPG
  API/CCW.Application/PdfFiles/sheriffMartinezSigBlue.JPG
  API/CCW.Application/Program.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/CCW.Document.csproj
Labels: main, API

#273 Pdfs to set UI part
  API/CCW.Application/Controllers/PermitApplicationController.cs
Labels: main, API

#274 Pdf
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Enum/ApplicationStatus.cs
  API/CCW.Application/PdfFiles/Application_Template.pdf
Labels: main, API

#275 #2271 #2175 #2176 #2250 #2152 - Fixes
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-admin/tests/unit/components/brand/__snapshots__/BrandForm.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/footer/__snapshots__/Footer.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/navigation/__snapshots__/SideBar.spec.ts.snap
  UI/libs/core-admin/tests/unit/components/search/__snapshots__/SearchBar.spec.ts.snap
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI

#276 #2211 - Manual Appointment Override
  UI/libs/core-admin/src/lib/components/appointment/DateTimePicker.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#278 fixed text.
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#279 Booth/admin validations
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/package-lock.json
Labels: main, UI

#283 fix
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
Labels: main, UI

#284 fix
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#287 AB#2331 update the review fields
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#286 fix: fix typos
  UI/libs/core-public/src/lib/views/PenalView.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#288 add defaults to config
  UI/libs/shared/ui/src/lib/stores/configStore.ts
Labels: main, UI

#289 Booth/admin style fixes
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#290 updated the styling to the checklist
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
Labels: main, UI

#291 AB#2405
  UI/.husky/pre-commit
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
Labels: main, UI

#293 updated the dark mode style and added button
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/appointment/DateTimePicker.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/RequestReasonTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/views/NotFoundView.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
Labels: main, UI
