Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2023-04, with the labels that each got.

#362 Feature/update styling
  UI/apps/admin/.eslintrc.json
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/.eslintrc.json
  UI/libs/core-admin/.eslintrc.json
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/appointment/DateTimePicker.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AliasesTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ImmigrationInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SaveButton.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-status/PermitStatus.vue
  UI/libs/core-admin/src/lib/components/templates/PageTemplate.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/.eslintrc.json
  UI/libs/shared/ui/.eslintrc.json
  UI/libs/shared/ui/src/lib/assets/vuetify.css
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/ui/src/lib/components/footer/Footer.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/src/lib/components/tables/AliasTable.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/.eslintrc.json
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#363 Feature/2181 admin print unofficial permit
  API/CCW.Admin/Controllers/AgencyProfileSettingsController.cs
  API/CCW.Admin/Mappers/EntityToAgencyProfileSettingsResponseModelMapper.cs
  API/CCW.Application/Clients/DocumentServiceClient.cs
  API/CCW.Application/Clients/IDocumentServiceClient.cs
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Models/AgencyProfileSettingsModel.cs
  API/CCW.Application/Program.cs
  API/CCW.Application/appsettings.Development.json
Labels: main, API

#367 Fix: Change colors to primary
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/CommentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/HistoryTab.vue
Labels: main, UI

#371 fix: update ui definition
  Deployment/IaC/Marketplace/createUiDefinition.json
Labels: main, IaC

#372 feat: update marketplace yaml
  Deployment/IaC/Marketplace/mainTemplate.json
  Deployment/Pipelines/azure-pipelines-mp-install.yml
Labels: main, IaC

#373 fix: capture events instead of functions
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#374 Fix: Application style and design
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ImmigrationInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
Labels: main, UI

#368 Feature/2487 update checklist name to avatar
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
Labels: main, UI

#376 task: fix colors of calendars and agency settings
  UI/libs/core-admin/src/lib/components/appointment/DateTimePicker.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/brand/BrandForm.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/AssetsFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ColorSchemeFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-admin/src/lib/views/NotFoundView.vue
  UI/libs/core-public/src/lib/components/navbar/NavBar.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
Labels: main, UI

#378 added script to add b2c app registration only
  Deployment/Scripts/B2C-Authentication/New-B2CAppRegistration.ps1
Labels: main, IaC

#379 Feature/2555 auth improvements
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/src/PublicApp.vue
  UI/libs/core-admin/src/lib/api/config.ts
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/login/LoginButton.vue
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/api/config.ts
  UI/libs/core-public/src/lib/api/interceptors.ts
  UI/libs/core-public/src/lib/components/login/LoginButton.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#380 fix: use provide/inject to maintain instance of MsalBrowser
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/api/interceptors.ts
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
Labels: main, UI

#381 Feature/2500 90 day countdown
  API/CCW.Application/Entities/Application.cs
  API/CCW.Application/Entities/UserApplication.cs
  API/CCW.Application/Mappers/PermitApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/PermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Mappers/UserPermitRequestApplicationToApplicationMapper.cs
  API/CCW.Application/Properties/launchSettings.json
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API
