Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-03, with the labels that each got.

#589 Task/3259 add employment license
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Enums/PaymentType.cs
  API/CCW.Common/Models/AgencyProfileSettings.cs
  API/CCW.Common/Models/CostType.cs
  API/CCW.Common/RequestModels/AgencyProfileSettingsRequestModel.cs
  API/CCW.Common/ResponseModels/AgencyProfileSettingsResponseModel.cs
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/cards/PendingEmploymentApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-admin/src/lib/views/HomeView.vue
  UI/libs/core-public/src/lib/components/containers/AcknowledgementContainer.vue
  UI/libs/core-public/src/lib/components/containers/FinalizeContainer.vue
  UI/libs/core-public/src/lib/components/containers/MoreInformationContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/PriceInfoDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/types/index.ts
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#590 feat: update assigned applications card
  UI/libs/core-admin/src/lib/components/cards/AssignedApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/NewAppointmentsCard.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
Labels: main, UI

#594 Task/renewal process
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Enums/ApplicationType.cs
  API/CCW.Common/Models/AgencyProfileSettings.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/QualifyingQuestionOne.cs
  API/CCW.Common/Models/QualifyingQuestionStandard.cs
  API/CCW.Common/Models/QualifyingQuestionTwelve.cs
  API/CCW.Common/Models/QualifyingQuestionTwo.cs
  API/CCW.Common/Models/SummarizedPermitApplication.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Common/RequestModels/AgencyProfileSettingsRequestModel.cs
  API/CCW.Common/ResponseModels/AgencyProfileSettingsResponseModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationResponseModel.cs
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/cards/ActiveLicensesCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingEmploymentApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingJudicalApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingReserveApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingStandardApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationTypeInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#595 feat: update date times to dateTimeOffset
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/Comment.cs
  API/CCW.Common/Models/Email.cs
  API/CCW.Common/Models/History.cs
  API/CCW.Common/Models/PaymentHistory.cs
  API/CCW.Common/Models/UploadedDocument.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Common/ResponseModels/HistoryResponseModel.cs
  API/CCW.Common/ResponseModels/PaymentHistoryResponseModel.cs
  API/CCW.Schedule/Entities/AppointmentManagement.cs
  API/CCW.Schedule/Entities/AppointmentWindow.cs
  API/CCW.Schedule/Models/AppointmentManagementRequestModel.cs
  API/CCW.Schedule/Models/AppointmentWindowCreateRequestModel.cs
  API/CCW.Schedule/Models/AppointmentWindowResponseModel.cs
  API/CCW.Schedule/Models/AppointmentWindowUpdateRequestModel.cs
  API/CCW.Schedule/Program.cs
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  API/CCW.Schedule/Services/Contracts/IAppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
Labels: main, UI, API

#596 fix online payments with renewals
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#597 feat: update submission process
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#598 feat: Change application update logic
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/SummarizedPermitApplication.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationResponseModel.cs
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#599 fix: application and official license not printing
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#600 Update en.json
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#601 Update SignatureStep.vue
  API/CCW.Common/Models/Agreements.cs
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#602 fix: update information route
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#603 Task/3313 previous address validation
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
Labels: main, UI

#604 feat: check previous address length
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
Labels: main, UI

#607 Bug/fix issue date
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/License.cs
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#608 Update en.json
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#610 update document info section
  UI/libs/shared/ui/src/lib/components/info-sections/DocumentInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#609 Feat/2600 add edit function to weapons table
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#605 feat: add application and appointment status filters
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Common/Models/SummarizedPermitApplication.cs
  API/CCW.Common/ResponseModels/ApplicationSummaryCountResponseModel.cs
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/cards/ActiveLicensesCard.vue
  UI/libs/core-admin/src/lib/components/cards/DeniedApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingEmploymentApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingJudicalApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingReserveApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/cards/PendingStandardApplicationsCard.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/components/tables/ApplicationTable.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI, API

#611 Bug/3324 application select
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
Labels: main, UI

#612 feat: update assigned applications, fix get applications endpoint
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Common/ResponseModels/ApplicationSummaryCountResponseModel.cs
  UI/apps/admin/src/AdminApp.vue
  UI/libs/core-admin/src/lib/components/cards/AssignedApplicationsCard.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#618 Feat/ci cd pipeline update
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC

#620 Feat/ci cd pipeline update
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC

#621 Feat/ci cd pipeline update
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC

#632 feat: update pipelines
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-api-pipeline-template.yml
  Deployment/Pipelines/azure-pipelines-ui.yml
  Deployment/Scripts/Remove-AdoIPRestrictions.psm1
Labels: main, IaC, API

#634 Feature/api ci cd
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC
