Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-07, with the labels that each got.

#774 Bug/3623 file renaming
  UI/libs/core-admin/src/lib/components/brand/steps/ConfigurationFormStep.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#775 fix: admin doc rename validation
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
Labels: main, UI

#777 hotfix: remove buttons temporarily
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#778 Hotfix/revert hotfix changes
  API/CCW.Schedule/Controllers/AppointmentController.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#779 Hotfix/revert hotfix changes
  API/CCW.Common/Models/AppointmentManagement.cs
  API/CCW.Common/RequestModels/AppointmentManagementRequestModel.cs
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentManagement.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#780 Task/3659 editable weapon modifications
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-public/src/lib/components/containers/ModifyFormContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifyWeaponStep.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#776 feat: update renewal and modify buttons.
  UI/libs/core-public/src/lib/components/dialogs/ConfirmDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#782 fix: hide days before renewal if already modifying or renewing
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#783 fix: last name being printed for middle name field
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#784 Feature/3646 ci cd saas
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-api-pipeline-template.yml
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC, API

#785 test: update pipeline trigger
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#795 Test/ci cd updates
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC, API

#796 Task/3632 print forms all caps
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#797 Update StartHereDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/StartHereDialog.vue
Labels: main, UI

#798 fix: parameterize resource group
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#799 Dev
  API/CCW.Admin/azure-admin-pipeline.yml
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Application/azure-application-pipeline.yml
  API/CCW.Document/azure-document-pipeline.yml
  API/CCW.Payment/azure-payment-pipeline.yml
  API/CCW.Schedule/azure-schedule-pipeline.yml
  API/CCW.UserProfile/azure-userprofile-pipeline.yml
  Deployment/Pipelines/azure-api-pipeline-template.yml
  Deployment/Pipelines/azure-pipelines-ui.yml
  UI/apps/admin/config/config.json
  UI/apps/public/config/config.json
  UI/libs/core-public/src/lib/components/dialogs/StartHereDialog.vue
Labels: main, UI, IaC, API

#801 Dev
  Deployment/Pipelines/azure-pipelines-ui.yml
Labels: main, IaC

#802 Hotfix/fix application pdf
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#803 Hotfix/fix application pdf
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#808 Fix/revocation pdf
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#809 Bug/3656 manual modification payment
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#810 feat: remove default values from weapons table
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#811 feat: update application table filters
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
Labels: main, UI

#812 Dev
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/dialogs/WeaponsDialog.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#813 fix: update safety certificate when modifying weapon
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#814 Feat/3664 add modification submission date
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/UserApplication.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#815 update dev from main
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/UserApplication.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#820 Task/3633 official license name
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/SummarizedPermitApplicationReport.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationReportResponseModel.cs
  UI/libs/core-public/src/lib/components/containers/ExistingApplicationContainer.vue
Labels: main, UI, API

#819 feat: add uat to network restrictions script
  Deployment/Pipelines/azure-api-pipeline-template.yml
Labels: main, IaC

#818 Feat/3642 modify admin user interface labels more noticeable
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
Labels: main, UI

#826 fix: enable radio group if updating question
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
Labels: main, UI

#827 fix: admin traffic table
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
Labels: main, UI

#828 feat: add customer interaction to history
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-public/src/lib/components/containers/ModifyFormContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifySupportingDocumentsStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI, API

#829 Feature/3688 historical applications
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Profiles/AutoMapperProfiles.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Common/Models/HistoricalApplicationSummary.cs
  API/CCW.Common/ResponseModels/HistoricalApplicationSummaryResponseModel.cs
  API/CCW.Common/ResponseModels/HistoryResponseModel.cs
  API/CCW.Common/ResponseModels/PaymentHistoryResponseModel.cs
  API/CCW.Common/ResponseModels/PermitApplicationResponseModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationReportResponseModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Common/ResponseModels/UserPermitApplicationResponseModel.cs
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#833 Update ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#834 Dev
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Profiles/AutoMapperProfiles.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Common/Models/HistoricalApplicationSummary.cs
  API/CCW.Common/ResponseModels/HistoricalApplicationSummaryResponseModel.cs
  API/CCW.Common/ResponseModels/HistoryResponseModel.cs
  API/CCW.Common/ResponseModels/PaymentHistoryResponseModel.cs
  API/CCW.Common/ResponseModels/PermitApplicationResponseModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationReportResponseModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Common/ResponseModels/UserPermitApplicationResponseModel.cs
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/containers/ModifyFormContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifySupportingDocumentsStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#839 fix: only export appointment complete for SID reports
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/views/ReportsView.vue
Labels: main, UI, API

#830 Feat/3685 change styling of receiptview/submission card for user readability
  UI/libs/core-public/src/lib/views/RecieptView.vue
Labels: main, UI

#770 Task/2860 modifiable signature
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/ModifySignatureDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SignatureInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/package-lock.json
Labels: main, UI

#841 Task/3684 update verbiages
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/core-public/src/lib/views/RecieptView.vue
Labels: main, UI

#842 Bug/3698 fix modification weapons deletion
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI

#843 fix: update appointment creation times
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
Labels: main, API

#844 Update SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
Labels: main, UI

#848 feat: reset payments no matter what to hide button
  API/CCW.Payment/Controllers/PaymentController.cs
Labels: main, API

#851 Task/3701 highlight appointment year
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#857 Bug/3703 fix assigned user
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#858 Dev
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#860 feat: sort admin users
  UI/libs/core-admin/src/lib/components/composables/sortAdminUsers.ts
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#861 fix: get correct modification type
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
Labels: main, UI

#863 Task/3713 heartland payment deletion
  UI/libs/core-admin/src/lib/components/dialogs/DeletePaymentDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/receipt/PaymentHistory.vue
Labels: main, UI

#865 task: add conditional logic for birth region on livescan form
  API/CCW.Application/Services/PdfService.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
Labels: main, UI, API

#864 Dev
  API/CCW.Application/Services/PdfService.cs
  Deployment/Pipelines/azure-api-pipeline-template.yml
  UI/libs/core-admin/src/lib/components/composables/sortAdminUsers.ts
  UI/libs/core-admin/src/lib/components/dialogs/DeletePaymentDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WeaponsTab.vue
  UI/libs/core-admin/src/lib/components/receipt/PaymentHistory.vue
Labels: main, UI, IaC, API

#866 Bug/3714 appointment creation
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
Labels: main, UI, API
