Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-06, with the labels that each got.

#712 Feature/3513 override email choice
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Common/Models/MatchRequest.cs
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmMatchApplicationDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmationDialog.vue
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/core-admin/src/lib/components/linking/UndoApplicationLink.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/views/ExistingApplicantsView.vue
  UI/libs/core-public/src/lib/components/containers/ExistingApplicationContainer.vue
  UI/libs/core-public/src/lib/components/containers/FileUploadContainer.vue
Labels: main, UI, API

#713 bug fix: approving background check items updates history twice
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BackgroundCheckTab.vue
Labels: main, UI

#714 fix: add AND statement
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#715 feat: update verbiage
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#716 Feat/3521 remove edit buttons from public application detail view
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationTypeInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CharacterReferenceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
Labels: main, UI

#717 feat: add max height to menu
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentManagement.vue
Labels: main, UI

#718 Task/3499 add legacy application pdf
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IDocumentAzureStorage.cs
  API/CCW.Application/Services/Contracts/IPdfService.cs
  API/CCW.Application/Services/DocumentAzureStorage.cs
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/QualifyingQuestionOne.cs
  API/CCW.Common/Models/QualifyingQuestionTwelve.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-admin/src/lib/components/brand/steps/DocumentFormStep.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/types/index.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#719 fix: don't allow weapon edits while verifying info
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
Labels: main, UI

#721 fix: update correct methods
  UI/libs/core-public/src/lib/components/containers/ModifyFormContainer.vue
Labels: main, UI

#720 Feature/3527 start here rework
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#722 fix: update which items get reset
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#724 feat: add match history to matched applications
  API/CCW.Application/Controllers/PermitApplicationController.cs
Labels: main, API

#725 feat: update application type selection on admin side
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#726 fix: existing application date format
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
Labels: main, UI

#727 Task/3498 livescan fees
  API/CCW.Common/Enums/PaymentType.cs
  API/CCW.Common/Models/Cost.cs
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/dialogs/PriceInfoDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#728 bug/3537 Admin: uploading docs for customer does not update list
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#729 feat: add state management for application routes
  UI/libs/core-public/src/lib/components/containers/ExistingApplicationContainer.vue
  UI/libs/core-public/src/lib/components/containers/MoreInformationContainer.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/stores/userStore.ts
Labels: main, UI

#730 Feat/3546 overwrite emails and add warning notification to dialog
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Common/Models/MatchRequest.cs
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmMatchApplicationDialog.vue
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI, API

#732 Feat/3525 improve button text for finalizing verifying information, make it clear that they're verifying, not submitting
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
Labels: main, UI

#734 pass in index instead of item
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
Labels: main, UI

#735 fix: nullable cost
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#737 feat: update readonly fields
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
Labels: main, UI

#738 Feature/3543 rework payment processing
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Common/Models/PaymentHistory.cs
  API/CCW.Common/RequestModels/UserPermitApplicationRequestModel.cs
  API/CCW.Common/ResponseModels/PaymentHistoryResponseModel.cs
  API/CCW.Payment/Controllers/PaymentController.cs
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/VerifyTransactionDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/receipt/PaymentHistory.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/stores/paymentStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#740 fix: additional application pages
  API/CCW.Application/Services/PdfService.cs
Labels: main, API

#739 feat/3569 make name text field consistent in application tab
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
Labels: main, UI

#742 fix: update token renewal
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
Labels: main, UI

#743 feat: reset payment history and regular history upon renewal
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#744 feat: rework payment and file upload dialogs
  UI/libs/core-admin/src/lib/components/dialogs/FileUploadDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#745 fix: update modified names
  UI/libs/core-public/src/lib/components/dialogs/WithdrawModifyDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#746 fix: add dashes to regex
  UI/libs/shared/ui/src/lib/rule-sets/ruleSets.ts
Labels: main, UI

#747 Bug/3563 employer number validation
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ContactInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
Labels: main, UI

#748 fix: button layout, verified manual payment
  UI/libs/core-admin/src/lib/components/dialogs/ReadyForPaymentDialog.vue
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
Labels: main, UI

#749 fix: remove unused injection
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
Labels: main, UI

#750 Bug/3582 deleting manual transaction does not persist
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI, API

#752 feat: update checklist requirements
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#751 feat: require safety certificate for renewals
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#754 fix: disable finish renewal and modification buttons if no payment
  UI/libs/core-admin/src/lib/components/dialogs/FinishModificationDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/FinishRenewalDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#753 Bug/3595 manual payment flag
  UI/libs/core-admin/src/lib/components/receipt/ReceiptForm.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#755 Bug/3564 appointment complete workflow
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Schedule/Controllers/AppointmentController.cs
  API/CCW.Schedule/Services/ApplicationCosmosDbService.cs
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  API/CCW.Schedule/Services/Contracts/IAppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/appointment/Appointments.vue
  UI/libs/core-admin/src/lib/components/appointment/Schedule.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/router/index.ts
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-admin/src/lib/stories/components/appointment/Appointments.stories.mdx
  UI/libs/core-admin/src/lib/views/AppointmentView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, API

#756 Bug/3560 modification license bug
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#757 fix: update delete dialog
  UI/libs/core-admin/src/lib/components/dialogs/DeletePaymentDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/PaymentDialog.vue
  UI/libs/core-admin/src/lib/components/receipt/PaymentHistory.vue
Labels: main, UI

#759 Feature/3618 matching UI
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Common/Enums/AppointmentStatus.cs
  API/CCW.Common/Enums/PaymentType.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AdminDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-public/src/lib/components/dialogs/StartHereDialog.vue
  UI/libs/core-public/src/lib/views/HomeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI, API

#758 Task/3565 add agreement instructions
  UI/libs/core-public/src/lib/components/dialogs/StartHereDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
Labels: main, UI

#761 Bug/3627 fix expiration date
  API/CCW.Application/Services/PdfService.cs
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI, API

#764 Bug/3601 mod form approval denial
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Enums/ApplicationStatus.cs
  API/CCW.Document/Controllers/DocumentController.cs
  UI/libs/core-admin/src/lib/components/brand/steps/DocumentFormStep.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/BirthInformationTab.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-public/src/lib/components/containers/ExistingApplicationContainer.vue
  UI/libs/core-public/src/lib/components/dialogs/StartHereDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#765 Bug/3635 assigned user
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/header/Header.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/components/dialogs/WithdrawRenewDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewContactInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/RenewPersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/components/dialogs/AliasDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/FileUploadInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
Labels: main, UI, API

#766 fix: hide issuance payment button until approved
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#767 Task/3637 licensing manager name
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Models/AgencyProfileSettings.cs
  API/CCW.Common/RequestModels/AgencyProfileSettingsRequestModel.cs
  API/CCW.Common/ResponseModels/AgencyProfileSettingsResponseModel.cs
  UI/libs/core-admin/src/lib/components/brand/steps/AgencyFormStep.vue
  UI/libs/shared/ui/src/lib/stores/brandStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#768 fix: use correct method instead of computed
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
Labels: main, UI

#769 fix: reset mod number when renewing
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI
