Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-05, with the labels that each got.

#606 Feature/3315 public payment
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Payment/Controllers/PaymentController.cs
  API/CCW.Payment/Program.cs
  UI/apps/admin/src/registerServiceWorker.js
  UI/libs/core-admin/src/lib/components/dialogs/ReadyForPaymentDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/DemographicsTab.vue
  UI/libs/core-admin/src/lib/plugins/vuetify.ts
  UI/libs/core-public/src/lib/components/dialogs/InitialPaymentConfirmationDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#669 feat: update verbiage
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI

#671 Task/2754 admin renew process
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Enums/ApplicationStatus.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Payment/Controllers/PaymentController.cs
  UI/libs/core-admin/src/lib/components/dialogs/FinishRenewalDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/ReadyForPaymentDialog.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/stores/documentsStore.ts
  UI/libs/core-public/src/lib/components/dialogs/RenewalPaymentConfirmationDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifySupportingDocumentsStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/composables/getOriginalApplicationType.ts
  UI/libs/shared/ui/src/lib/stores/completeApplication.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#672 fix: renewal button logic
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#673 fix: document builder
  API/CCW.Application/Services/PdfService.cs
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI, API

#675 Task/2589 add admonishment to out of state
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#677 Task/official license
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/Contracts/IDocumentAzureStorage.cs
  API/CCW.Application/Services/Contracts/IPdfService.cs
  API/CCW.Application/Services/DocumentAzureStorage.cs
  API/CCW.Application/Services/PdfService.cs
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, API

#676 Task/2589 add admonishment to out of state
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
Labels: main, UI

#678 feat: update application table sorting
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/core-admin/src/lib/components/linking/UndoApplicationLink.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
Labels: main, UI, API

#679 fixed styling to match question 1
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
Labels: main, UI

#681 fix: add user profile endpoints to admin user profile controller
  API/CCW.UserProfile/Controllers/AdminUserController.cs
  API/CCW.UserProfile/Controllers/UserProfileController.cs
Labels: main, API

#680 feat: move modification payment to later in process
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Payment/Controllers/PaymentController.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-public/src/lib/components/dialogs/PaymentConfirmationDialog.vue
  UI/libs/core-public/src/lib/components/dialogs/RenewalPaymentConfirmationDialog.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifyWeaponStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#685 Task/3424 update button logic
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
Labels: main, UI

#690 fix: update legacy application matching
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#691 fix button logic
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
Labels: main, UI

#693 fix: incorrect document type
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
Labels: main, UI

#694 Bug/3473 fix weapons table max out at 10
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#697 fix: issue and exp date not setting properly
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#696 Bug/3495 legacy qualifying questions
  API/CCW.Common/Models/UserApplication.cs
  UI/libs/core-admin/src/lib/components/dialogs/QualifyingQuestionOneDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/QualifyingQuestionStandardDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/QualifyingQuestionTwelveDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/QualifyingQuestionTwoDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/ReviewDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/LegacyQualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/qualifying-questions/DeniedLicenseQualifyingQuestion.vue
  UI/libs/core-public/src/lib/components/qualifying-questions/PriorLicenseQualifyingQuestion.vue
  UI/libs/core-public/src/lib/components/qualifying-questions/StandardQualifyingQuestion.vue
  UI/libs/core-public/src/lib/components/qualifying-questions/TrafficQualifyingQuestion.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/locales/en.json
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#698 Bug/admin legacy questions
  UI/libs/core-admin/src/lib/components/dialogs/LegacyQualifyingQuestionEightDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/LegacyQualifyingQuestionOneDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/LegacyQualifyingQuestionStandardDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/LegacyQualifyingQuestionTwoDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#700 fix: change default date to 'not scheduled'
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#701 Feature/3497 existing applicant no application
  API/CCW.Common/RequestModels/UserProfileRequestModel.cs
  API/CCW.UserProfile/Controllers/UserProfileController.cs
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmMatchApplicationDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmUserNoApplicationDialog.vue
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/shared/ui/src/lib/api/endpoints.ts
  UI/libs/shared/ui/src/lib/stores/userStore.ts
Labels: main, UI, API

#704 fix: bug fixes
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/components/templates/AppointmentManagement.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#686 Bug/2886 public application detail edit redirect
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AliasInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AppearanceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ApplicationTypeInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CharacterReferenceInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/CitizenInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/ContactInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/DOBinfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/IdInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PersonalInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/PreviousAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/QualifyingQuestionsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
Labels: main, UI

#706 fix: save filters on application table
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#707 fix: add appropriate days for multiple days of the week
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
Labels: main, API

#708 fix: remove status filter from legacy options
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
Labels: main, UI

#709 Marketplace package
  Deployment/IaC/Marketplace/mainTemplate.json
  Deployment/Pipelines/azure-pipelines-mp-install.yml
Labels: main, IaC

#710 Feature/3489 existing application user experience
  UI/libs/core-admin/src/lib/components/dialogs/ConfirmMatchApplicationDialog.vue
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
Labels: main, UI

#711 Feature/3506 copy legacy application emails
  API/CCW.Application/Controllers/PermitApplicationController.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/Contracts/IApplicationCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/linking/LinkExistingApplications.vue
  UI/libs/core-admin/src/lib/components/linking/UndoApplicationLink.vue
  UI/libs/core-admin/src/lib/components/navigation/SideBar.vue
  UI/libs/core-admin/src/lib/stores/permitsStore.ts
  UI/libs/shared/ui/src/lib/api/endpoints.ts
Labels: main, UI, API
