Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-08, with the labels that each got.

#870 Dev
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/templates/AppointmentTemplate.vue
Labels: main, UI, API

#867 Update PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
Labels: main, UI

#871 Update AppointmentCosmosDbService.cs
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
Labels: main, API

#872 Dev
  API/CCW.Schedule/Services/AppointmentCosmosDbService.cs
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
Labels: main, UI, API

#873 fix: legacy qualifying question review
  UI/libs/core-admin/src/lib/components/dialogs/ReviewDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#874 Update ReviewDialog.vue
  UI/libs/core-admin/src/lib/components/dialogs/ReviewDialog.vue
Labels: main, UI

#875 Dev
  UI/libs/core-admin/src/lib/components/dialogs/ReviewDialog.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#876 task: add confirmation dialog to modification approval
  UI/libs/core-admin/src/lib/components/dialogs/ApproveModificationDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI

#877 Dev
  UI/libs/core-admin/src/lib/components/dialogs/ApproveModificationDialog.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard1.vue
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
Labels: main, UI
