Repository SanDiegoCountySheriff/CSSA-CCW, pull requests merged in 2024-04, with the labels that each got.

#631 fix: invalid prop type console error
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
Labels: main, UI

#616 Feat/2600 add edit function to weapons table
  UI/libs/shared/ui/src/lib/components/info-sections/WeaponsInfoSection.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#593 Feature/2759 modification process
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
  API/CCW.Application/Services/PdfService.cs
  API/CCW.Common/Enums/PaymentType.cs
  API/CCW.Common/Models/Address.cs
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/BackgroundCheck.cs
  API/CCW.Common/Models/History.cs
  API/CCW.Common/Models/MailingAddress.cs
  API/CCW.Common/Models/PersonalInfo.cs
  API/CCW.Common/Models/SpouseAddressInformation.cs
  API/CCW.Common/Models/SummarizedPermitApplication.cs
  API/CCW.Common/Models/UserApplication.cs
  API/CCW.Common/Models/WorkInformation.cs
  API/CCW.Common/RequestModels/PermitApplicationRequestModel.cs
  API/CCW.Common/ResponseModels/SummarizedPermitApplicationResponseModel.cs
  API/CCW.Payment/Controllers/PaymentController.cs
  API/CCW.Payment/appsettings.Development.json
  UI/libs/core-admin/src/lib/components/permits/permit-cards/PermitCard2.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/PermitDetail.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AddressInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/ApplicantInfoTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/AttachedDocumentsTab.vue
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/WorkInfoTab.vue
  UI/libs/core-admin/src/lib/components/receipt/PaymentHistory.vue
  UI/libs/core-admin/src/lib/components/search/SearchBar.vue
  UI/libs/core-public/src/lib/components/containers/ModifyFormContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentButtonContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormSecondStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepHeader.vue
  UI/libs/core-public/src/lib/components/form-stepper/FormStepItems.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifyAddressStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifyNameStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifySupportingDocumentsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/modify-form-steps/ModifyWeaponStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/router/index.ts
  UI/libs/core-public/src/lib/router/routes.ts
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/core-public/src/lib/views/ModifyFinalizeView.vue
  UI/libs/core-public/src/lib/views/ModifyFormView.vue
  UI/libs/shared/ui/src/lib/components/dialogs/PreviousAddressDialog.vue
  UI/libs/shared/ui/src/lib/components/info-sections/AddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/EmploymentInfoSection.vue
  UI/libs/shared/ui/src/lib/components/info-sections/SpouseAddressInfoSection.vue
  UI/libs/shared/ui/src/lib/components/tables/AddressTable.vue
  UI/libs/shared/ui/tests/unit/components/info-sections/AddressInfoSection.spec.ts
  UI/libs/shared/ui/tests/unit/components/tables/AddressTable.spec.ts
  UI/libs/shared/utils/src/lib/formatters/defaultFormatters.ts
  UI/libs/shared/utils/src/lib/lists/defaultConstants.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#638 Task/3328 polish submission screen
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/containers/PaymentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FinalizeWrapper.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
  UI/libs/shared/ui/src/lib/stores/appointmentsStore.ts
Labels: main, UI

#639 fix: name whitespace
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
Labels: main, UI

#640 feat: add cors
  API/CCW.Admin/Program.cs
  API/CCW.Admin/appsettings.Development.json
  API/CCW.Application/Program.cs
  API/CCW.Application/appsettings.Development.json
  API/CCW.Document/Program.cs
  API/CCW.Document/appsettings.Development.json
  API/CCW.Payment/Program.cs
  API/CCW.Payment/appsettings.Development.json
  API/CCW.Schedule/Program.cs
  API/CCW.Schedule/appsettings.Development.json
  API/CCW.UserProfile/Program.cs
  API/CCW.UserProfile/appsettings.Development.json
Labels: main, API

#641 feat: calculate image height dynamically
  API/CCW.Document/Program.cs
  UI/libs/core-public/src/lib/views/HomeView.vue
Labels: main, UI, API

#642 Update FileUploadContainer.vue
  UI/libs/core-public/src/lib/components/containers/FileUploadContainer.vue
Labels: main, UI

#644 Bug/3368 mobile appointments
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/views/ApplicationDetailView.vue
Labels: main, UI

#643 task: add validation to application type
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
Labels: main, UI

#645 fix: adding weapons after editing
  UI/libs/shared/ui/src/lib/components/tables/WeaponsTable.vue
Labels: main, UI

#646 fix: updating application
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
Labels: main, UI

#647 fix: remove convenience fee, make credit fee percent, fix floating point
  API/CCW.Common/Models/Cost.cs
  API/CCW.Common/Models/CostType.cs
  UI/libs/core-admin/src/lib/components/brand/steps/FeesFormStep.vue
Labels: main, UI, API

#649 Update AdminApp.vue
  UI/apps/admin/src/AdminApp.vue
Labels: main, UI

#648 fix: update qualifying question ui on mobile
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
Labels: main, UI

#652 task: add application insights to ui
  UI/apps/admin/config/config.json
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/config/config.json
  UI/apps/public/src/PublicApp.vue
  UI/libs/shared/ui/src/lib/api/auth/authentication.ts
  UI/libs/shared/ui/src/lib/stores/configStore.ts
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
  UI/package-lock.json
  UI/package.json
Labels: main, UI

#653 move app insight
  UI/apps/admin/src/AdminApp.vue
  UI/apps/admin/src/main.ts
  UI/apps/public/src/PublicApp.vue
  UI/apps/public/src/main.ts
Labels: main, UI

#655 add custom referrer property
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/src/PublicApp.vue
Labels: main, UI

#656 feat: add legacy qualifying questions
  API/CCW.Common/Models/Application.cs
  API/CCW.Common/Models/LegacyQualifyingQuestions.cs
Labels: main, API

#657 Update en.json
  UI/libs/shared/ui/src/lib/locales/en.json
Labels: main, UI

#659 feat: add traffic violations explanation and text areas
  API/CCW.Common/Models/QualifyingQuestionTwelve.cs
  UI/libs/core-admin/src/lib/components/permits/permit-detail/tabs/SurveyInfoTab.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/shared/utils/src/lib/types/defaultTypes.ts
Labels: main, UI, API

#658 fix: add validation to qualifying question 12
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
Labels: main, UI

#660 Update QualifyingQuestionEight.cs
  API/CCW.Common/Models/QualifyingQuestionEight.cs
Labels: main, API

#661 fix: make dark mode persist between sessions
  UI/apps/admin/src/AdminApp.vue
  UI/apps/public/src/PublicApp.vue
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
Labels: main, UI

#663 fix: update clarity of buttons and form
  UI/libs/core-public/src/lib/components/containers/AppointmentContainer.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/AddressInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/ApplicationTypeStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/FileUploadStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/IdBirthInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/PersonalInfoStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/QualifyingQuestionsStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/SignatureStep.vue
  UI/libs/core-public/src/lib/components/form-stepper/form-steps/WorkInfoStep.vue
  UI/libs/core-public/src/lib/components/wrappers/FormWrapper.vue
  UI/libs/core-public/src/lib/views/FinalizeView.vue
  UI/libs/shared/ui/src/lib/components/containers/FormButtonContainer.vue
  UI/libs/shared/ui/src/lib/components/mode/ThemeMode.vue
Labels: main, UI

#666 feat: add legacy container
  API/CCW.Application/Program.cs
  API/CCW.Application/Services/ApplicationCosmosDbService.cs
Labels: main, API

#665 feat: create dialogs for check in and no show
  UI/libs/core-admin/src/lib/components/dialogs/AppointmentActionConfirmationDialog.vue
  UI/libs/core-admin/src/lib/components/permits/Permits.vue
Labels: main, UI
